# Generated by Django 5.0.6 on 2025-09-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ekleyen_id',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='kayit_tarihi',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='darkTheme',
            new_name='isDark',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='payments',
        ),
    ]
