# Generated by Django 5.2.13 on 2026-06-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='E-posta Bildirimi'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='NetGSM formatı: 5XXXXXXXXX', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_enabled',
            field=models.BooleanField(default=False, verbose_name='SMS Bildirimi'),
        ),
    ]
