# Generated by Django 5.2.13 on 2026-06-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_enabled_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Sistem Yöneticisi'), (2, 'Operatör'), (3, 'Normal Kullanıcı'), (4, 'Bakanlık Kullanıcısı')], default=3, help_text='Rol', null=True, verbose_name='Rol'),
        ),
    ]
