# Generated by Django 5.2.13 on 2026-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_timeout_minutes',
            field=models.IntegerField(choices=[(0, 'Tarayıcı kapanınca'), (60, '1 saat'), (240, '4 saat'), (480, '8 saat'), (720, '12 saat'), (1440, '1 gün'), (10080, '7 gün'), (43200, '30 gün')], default=480, help_text='Oturumun otomatik düşeceği süre (0 = tarayıcı kapanınca)', verbose_name='Oturum Süresi'),
        ),
    ]
