# Generated by Django 5.2.13 on 2026-04-18 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(choices=[('con_1', 'Bağlantı-1'), ('con_2', 'Bağlantı-2'), ('con_3', 'Bağlantı-3')], default='con_1', help_text='Bağlantı Adı', max_length=10, verbose_name='Bağlantı Adı')),
                ('communication_type', models.CharField(choices=[('modbus', 'Modbus'), ('ascii', 'Ascii')], default='modbus', help_text='Haberleşme Tipi', max_length=10, verbose_name='Haberleşme Tipi')),
                ('con_type', models.CharField(choices=[('tcp', 'TCP/IP'), ('serial', 'SERIAL')], default='tcp', help_text='Bağlantı Tipi', max_length=10, verbose_name='Bağlantı Tipi')),
                ('con_mode', models.CharField(choices=[('rtu', 'RTU'), ('ascii', 'ASCII')], default='rtu', help_text='Bağlantı Modu', max_length=10, verbose_name='Bağlantı Modu')),
                ('con_address', models.CharField(blank=True, help_text='COM4 or 192.168.1.1', max_length=15, null=True, verbose_name='Bağlantı Adresi')),
                ('port', models.IntegerField(default=502, help_text='Port Numarası', verbose_name='Port')),
                ('baudrate', models.IntegerField(choices=[(300, 300), (600, 600), (1200, 1200), (2400, 2400), (4800, 4800), (9600, 9600), (14400, 14400), (19200, 19200)], default=9600, verbose_name='Bant Genişliği')),
                ('parity', models.IntegerField(choices=[(0, 'None Parity'), (1, 'Odd Parity'), (2, 'Even Parity')], default=0, verbose_name='Parity')),
                ('stop_bits', models.IntegerField(choices=[(0, '1 Stop Bit'), (1, '2 Stop Bit')], default=0, verbose_name='Stop Bits')),
                ('byte_size', models.IntegerField(choices=[(8, '8 Data Bits'), (7, '7 Data Bits')], default=8, verbose_name='Byte Size')),
                ('xonxoff', models.BooleanField(default=False, verbose_name='Xonxoff')),
                ('rtscts', models.BooleanField(default=False, verbose_name='Rstcts')),
                ('dsrdtr', models.BooleanField(default=False, verbose_name='Dsrdtr')),
                ('status', models.BooleanField(default=True, help_text='Aktif', verbose_name='Aktif')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bağlantılar',
                'db_table': 'connection',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Log Tipi Adı')),
            ],
            options={
                'verbose_name_plural': 'Log Tipleri',
                'db_table': 'log_type',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parametre Adı')),
                ('parameter_txt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parametre Txt')),
                ('unit', models.CharField(blank=True, max_length=150, null=True, verbose_name='Parametre Birim')),
                ('unit_txt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parametre Birim Txt')),
                ('channel_number', models.IntegerField(blank=True, null=True, verbose_name='Kanal No')),
                ('device_channel_id', models.CharField(blank=True, help_text='Uzak cihaz tarafındaki kanal kimliği (UUID vb.)', max_length=250, null=True, verbose_name='Cihaz Kanal ID')),
                ('gec_min', models.FloatField(blank=True, null=True, verbose_name='Geçerli Veri Min')),
                ('gec_max', models.FloatField(blank=True, null=True, verbose_name='Geçerli Veri Max')),
                ('olcum_min', models.FloatField(blank=True, null=True, verbose_name='Ölçüm Altı')),
                ('olcum_max', models.FloatField(blank=True, null=True, verbose_name='Ölçüm Üstü')),
                ('min_range', models.FloatField(blank=True, null=True, verbose_name='Range Min')),
                ('max_range', models.FloatField(blank=True, null=True, verbose_name='Range Max')),
            ],
            options={
                'verbose_name_plural': 'Parametreler',
                'db_table': 'parameter',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Makine-okur kod (örn. 'operator', 'auto_scenario')", max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(help_text='İnsan-okur ad', max_length=100, verbose_name='Ad')),
            ],
            options={
                'verbose_name_plural': 'Talep Tipleri',
                'db_table': 'request_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Makine-okur kod (örn. 'wastewater_domestic')", max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(help_text='İstasyon tipi adı', max_length=100, verbose_name='Ad')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name_plural': 'İstasyon Tipleri',
                'db_table': 'station_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Kod Numarası')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Status Kod Adı')),
            ],
            options={
                'verbose_name_plural': 'Status Kodları',
                'db_table': 'status_code',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Request Url')),
                ('data', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Request Data')),
                ('header', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Request Header')),
                ('param', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Request Param')),
                ('token', models.CharField(blank=True, max_length=250, null=True, verbose_name='Token')),
                ('response', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Response')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='Status Kod')),
                ('time_iso', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logtype')),
            ],
            options={
                'verbose_name_plural': 'Api Log Kayıtları',
                'db_table': 'api_log',
                'ordering': ['-time_iso'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.IntegerField(blank=True, choices=[(0, 'Analog Input'), (1, 'Analog Output'), (2, 'Dijital Input'), (3, 'Dijital Output')], default=0, null=True, verbose_name='Sensör Tipi')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sensör Marka')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sensör Model')),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Seri No')),
                ('signal_type', models.IntegerField(blank=True, choices=[(0, '4-20mA'), (1, '0-20mA'), (2, '0-10mV')], default=0, null=True, verbose_name='Sinyal Tipi')),
                ('slave_id', models.IntegerField(blank=True, default=1, null=True, verbose_name='Slave ID')),
                ('byte_order', models.CharField(blank=True, choices=[('little', 'Endian.Little'), ('big', 'Endian.Big')], default='big', max_length=20, null=True, verbose_name='Byte Order')),
                ('word_order', models.CharField(blank=True, choices=[('little', 'Endian.Little'), ('big', 'Endian.Big')], default='little', max_length=20, null=True, verbose_name='Word Order')),
                ('ascii_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ascii Kod')),
                ('address', models.IntegerField(blank=True, help_text='Modbus/Ascii Adresi/Sırası', null=True, verbose_name='Haberleşme Adresi')),
                ('quantity', models.IntegerField(blank=True, default=2, null=True, verbose_name='Adres Aralığı')),
                ('function', models.IntegerField(blank=True, choices=[(1, 'Read Coils'), (2, 'Read Discrete Inputs'), (3, 'Read Holding Registers'), (4, 'Read Input Registers'), (5, 'Write Single Coil'), (6, 'Write Single Register'), (15, 'Write Multiple Coils'), (16, 'Write Multiple Registers')], default=3, null=True, verbose_name='Fonksiyon')),
                ('decode', models.CharField(blank=True, choices=[('float32', '32 Bit Float'), ('float64', '64 Bit Float'), ('hex', 'Hex'), (None, 'Raw Data')], default='float32', max_length=20, null=True, verbose_name='Decode')),
                ('digital_inverse', models.BooleanField(default=False, verbose_name='Dijital Ters mi ?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.connection', verbose_name='Bağlantı')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.parameter')),
            ],
            options={
                'verbose_name_plural': 'Sensörler',
                'db_table': 'sensor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutputRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Değer')),
                ('is_completed', models.BooleanField(default=False)),
                ('request_code', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.requesttype', verbose_name='Talep Tipi')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_requests', to='api.sensor')),
            ],
            options={
                'verbose_name_plural': 'Dijital Out Talepleri',
                'db_table': 'output_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'Span'), (2, 'Multi')], null=True, verbose_name='Kalibrasyon Tipi')),
                ('period', models.IntegerField(blank=True, default=60, null=True, verbose_name='Kalibrasyon Periyodu')),
                ('cal_ref', models.FloatField(blank=True, null=True, verbose_name='Referans Değer')),
                ('cal_average', models.FloatField(blank=True, null=True, verbose_name='Ortalama Değer')),
                ('cal_std', models.FloatField(blank=True, null=True, verbose_name='Standart Sapma')),
                ('is_valid', models.BooleanField(blank=True, null=True, verbose_name='Geçerli mi ?')),
                ('time_iso', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='api.sensor')),
            ],
            options={
                'verbose_name_plural': 'Kalibrasyon Kayıtları',
                'db_table': 'calibration',
                'ordering': ['-time_iso'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='İstasyon Adı', max_length=100, verbose_name='İstasyon Adı')),
                ('address', models.CharField(blank=True, default='', help_text='İstasyon Adresi', max_length=250, verbose_name='İstasyon Adresi')),
                ('domain', models.URLField(blank=True, default='', help_text='İstasyonun bağlı olduğu uygulamanın domaini', max_length=100, verbose_name='Domain')),
                ('port', models.IntegerField(blank=True, default=443, help_text='Port No', null=True, verbose_name='Port No')),
                ('company', models.CharField(blank=True, default='', help_text='Kurum Adı', max_length=100, verbose_name='Kurum Adı')),
                ('active', models.BooleanField(default=True, help_text='Aktif mi?', verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample_request_sensor', models.ForeignKey(blank=True, help_text='StartSample servisinin tetikleyeceği dijital-out sensörü', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.sensor', verbose_name='Numune Alma Sensörü')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stationtype', verbose_name='İstasyon Tipi')),
            ],
            options={
                'verbose_name_plural': 'İstasyon Bilgileri',
                'db_table': 'station',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Uzak cihazın benzersiz kimliği (SIM ID / datalogger seri)', max_length=100, verbose_name='Cihaz ID')),
                ('code', models.CharField(help_text='İstasyon Kodu', max_length=50, verbose_name='İstasyon Kodu')),
                ('name', models.CharField(help_text='Cihaz Adı', max_length=200, verbose_name='Cihaz Adı')),
                ('data_period', models.IntegerField(blank=True, default=1, help_text='Veri Periyodu (dk)', null=True, verbose_name='Veri Periyodu (dk)')),
                ('auth_username', models.CharField(help_text='Uzak cihaza erişim kullanıcı adı', max_length=50, verbose_name='Kullanıcı Adı')),
                ('auth_secret', models.CharField(help_text='Uzak cihaza erişim şifresi', max_length=255, verbose_name='Erişim Şifresi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_devices', to='api.station')),
            ],
            options={
                'verbose_name_plural': 'Uzak Cihazlar',
                'db_table': 'remote_device',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('time_iso', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_offs', to='api.station')),
            ],
            options={
                'verbose_name_plural': 'Kapalı Kalma Kayıtları',
                'db_table': 'power_off',
                'ordering': ['-time_iso'],
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.station'),
        ),
        migrations.CreateModel(
            name='SensorLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.FloatField(blank=True, default=0, null=True, verbose_name='Anlık Değer')),
                ('readtime', models.DateTimeField(blank=True, null=True, verbose_name='Okuma Zamanı')),
                ('factorA', models.FloatField(blank=True, default=1, help_text='result = ax+b', null=True, verbose_name='Kalibrasyon Faktörü (A)')),
                ('factorB', models.FloatField(blank=True, default=0, help_text='result = ax+b', null=True, verbose_name='Kalibrasyon Faktörü (B)')),
                ('send_status', models.BooleanField(default=False, verbose_name='Status Gönderilsin mi ?')),
                ('is_random', models.BooleanField(default=False, verbose_name='Rastgele üret')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest', to='api.sensor')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statuscode')),
            ],
            options={
                'verbose_name_plural': 'Sensör Anlık Veriler',
                'db_table': 'sensor_latest',
                'ordering': ['sensor'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Değer')),
                ('time_iso', models.DateTimeField(blank=True, null=True, verbose_name='Kayıt Tarihi')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.sensor', verbose_name='Sensör')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statuscode')),
            ],
            options={
                'verbose_name_plural': 'Okumalar',
                'db_table': 'reading',
                'ordering': ['-time_iso'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Açıklama')),
                ('time_iso', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='api.station')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logtype')),
            ],
            options={
                'verbose_name_plural': 'Sistem Log Kayıtları',
                'db_table': 'system_log',
                'ordering': ['-time_iso'],
            },
        ),
    ]
