# Generated by Django 5.0.6 on 2025-09-03 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='İstasyon Adı', max_length=100, verbose_name='İstasyon Adı')),
                ('station_type', models.CharField(choices=[(1, 'Evsel Atıksu'), (2, 'Endüstriyel Atıksu'), (3, 'Kentsel Atıksu')], default=1, max_length=10)),
                ('address', models.CharField(blank=True, help_text='İstasyon Adresi', max_length=250, verbose_name='İstasyon Adresi')),
                ('domain', models.URLField(blank=True, default='sais.onlinecevre.com.tr', help_text='İstasyon Domain', max_length=100, verbose_name='sais.onlinecevre.com.tr')),
                ('port', models.IntegerField(blank=True, default=443, help_text='Port No', null=True, verbose_name='Port No')),
                ('company', models.CharField(blank=True, default='Envisoft', help_text='Kurum Adı', max_length=100, verbose_name='Kurum Adı')),
                ('active', models.BooleanField(default=True, help_text='Aktif mi?', null=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'İstasyon Bilgileri',
                'db_table': 'station',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_id', models.CharField(help_text='İstasyon ID', max_length=100, verbose_name='İstasyon ID')),
                ('code', models.CharField(default='30060001', help_text='İstasyon Kodu', max_length=50, verbose_name='İstasyon Kodu')),
                ('name', models.CharField(help_text='İstasyon Adı', max_length=200, verbose_name='İstasyon Adı')),
                ('data_period', models.IntegerField(blank=True, default=1, help_text='Veri Periyodu (dk)', null=True, verbose_name='Veri Periyodu (dk)')),
                ('username', models.CharField(help_text='Sim Kullanıcı Adı', max_length=50, verbose_name='Sim Kullanıcı Adı')),
                ('password', models.CharField(help_text='Sim Şifre', max_length=50, verbose_name='Sim Şifre')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stationinfo')),
            ],
            options={
                'verbose_name_plural': 'İstasyon Bilgileri',
                'db_table': 'sim_info',
                'ordering': ['created_at'],
            },
        ),
    ]
