# Generated by Django 5.2.13 on 2026-04-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='decode',
        ),
        migrations.AddField(
            model_name='sensor',
            name='ascii_line_terminator',
            field=models.CharField(blank=True, choices=[('\r\n', 'CRLF'), ('\n', 'LF'), ('\r', 'CR')], max_length=4, null=True, verbose_name='Satır Sonu'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='ascii_request',
            field=models.CharField(blank=True, help_text='Request-response ASCII için cihaza gönderilecek komut', max_length=100, null=True, verbose_name='ASCII İstek Komutu'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='ascii_response_regex',
            field=models.CharField(blank=True, help_text='Değeri ayıklamak için regex; ilk capture group değer olarak alınır', max_length=250, null=True, verbose_name="ASCII Yanıt Regex'i"),
        ),
        migrations.AddField(
            model_name='sensor',
            name='bit_position',
            field=models.IntegerField(blank=True, help_text="data_type='bit' için register içindeki bit indeksi (0-15)", null=True, verbose_name='Bit Pozisyonu'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='data_type',
            field=models.CharField(blank=True, choices=[('int16', 'Int16 (signed)'), ('uint16', 'UInt16 (unsigned)'), ('int32', 'Int32 (signed)'), ('uint32', 'UInt32 (unsigned)'), ('int64', 'Int64 (signed)'), ('uint64', 'UInt64 (unsigned)'), ('float32', 'Float32 (IEEE-754)'), ('float64', 'Float64 (IEEE-754)'), ('bool', 'Bool (coil / 1-bit)'), ('bit', 'Bit (register içinden bit_position)'), ('string', 'String (ASCII metin)'), ('raw', 'Raw bytes')], default='float32', help_text="Raw byte/register'ların nasıl yorumlanacağı", max_length=20, null=True, verbose_name='Veri Tipi'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='offset',
            field=models.FloatField(default=0.0, help_text='engineering_value = raw * scale + offset', verbose_name='Ofset (offset)'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='poll_interval_sec',
            field=models.IntegerField(blank=True, help_text='Null ise bağlantı seviyesi varsayılanı kullanılır', null=True, verbose_name='Okuma Periyodu (sn)'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='retry_count',
            field=models.IntegerField(default=1, help_text='Hatalı okumada tekrar deneme sayısı', verbose_name='Retry Sayısı'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='scale',
            field=models.FloatField(default=1.0, help_text='engineering_value = raw * scale + offset', verbose_name='Ölçek (scale)'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='timeout_ms',
            field=models.IntegerField(default=2000, help_text='Tek okuma için maksimum bekleme süresi', verbose_name='Timeout (ms)'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='address',
            field=models.IntegerField(blank=True, help_text='Modbus register adresi / ASCII kayıt sırası', null=True, verbose_name='Haberleşme Adresi'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ascii_code',
            field=models.CharField(blank=True, help_text="Multi-drop ASCII bus'larda cihaz/node adresi", max_length=20, null=True, verbose_name='ASCII Cihaz Adresi'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='quantity',
            field=models.IntegerField(blank=True, default=2, help_text='Okunacak register sayısı', null=True, verbose_name='Adres Aralığı'),
        ),
    ]
