# Generated by Django 5.0.6 on 2025-09-05 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(choices=[('con_1', 'Bağlantı-1'), ('con_2', 'Bağlantı-2'), ('con_3', 'Bağlantı-3')], default='con_1', help_text='Bağlantı Adı', max_length=10, null=True, verbose_name='Bağlantı Adı')),
                ('communication_type', models.CharField(choices=[('modbus', 'Modbus'), ('ascii', 'Ascii')], default='modbus', help_text='Haberleşme Tipi', max_length=10, null=True, verbose_name='Haberleşme Tipi')),
                ('con_type', models.CharField(choices=[('tcp', 'TCP/IP'), ('serial', 'SERIAL')], default='tcp', help_text='Bağlantı Tipi', max_length=10, null=True, verbose_name='Bağlantı Tipi')),
                ('con_mode', models.CharField(choices=[('rtu', 'RTU'), ('ascii', 'ASCII')], default='rtu', help_text='Bağlantı Modu', max_length=10, null=True, verbose_name='Bağlantı Modu')),
                ('con_address', models.CharField(help_text='COM4 or 192.168.1.1', max_length=10, null=True, verbose_name='Bağlantı Adresi')),
                ('port', models.IntegerField(default=502, help_text='Port Numarası', null=True, verbose_name='Port')),
                ('baudrate', models.IntegerField(choices=[(300, 300), (600, 600), (1200, 1200), (2400, 2400), (4800, 4800), (9600, 9600), (14400, 14400), (19200, 19200)], default=9600, help_text='Bant Genişliği', verbose_name='Bant Genişliği')),
                ('parity', models.IntegerField(choices=[(0, 'None Parity'), (1, 'Odd Parity'), (2, 'Even Parity')], default=0, help_text='Parity', verbose_name='Parity')),
                ('stop_bits', models.IntegerField(choices=[(0, '1 Stop Bit'), (1, '2 Stop Bit')], default=0, help_text='Stop Bits', verbose_name='Stop Bits')),
                ('byte_size', models.IntegerField(choices=[(8, '8 Data Bits'), (7, '7 Data Bits')], default=8, help_text='Byte Size', verbose_name='Byte Size')),
                ('xonxoff', models.BooleanField(default=False, verbose_name='Xonxoff')),
                ('rtscts', models.BooleanField(default=False, verbose_name='Rstcts')),
                ('dsrdtr', models.BooleanField(default=False, verbose_name='Dsrdtr')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Aktif', verbose_name='Aktif')),
            ],
            options={
                'verbose_name_plural': 'Connections',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='siminformation',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Sim Bilgileri'},
        ),
        migrations.AlterField(
            model_name='siminformation',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='domain',
            field=models.URLField(blank=True, default='sais.onlinecevre.com.tr', help_text='İstasyon Domain', max_length=100, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
