# Generated by Django 5.2.13 on 2026-06-10 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='command',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden Kullanıcı'),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_backups', to=settings.AUTH_USER_MODEL, verbose_name='Tetikleyen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='databaserestore',
            name='source_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='api.databasebackup', verbose_name='Kaynak Yedek'),
        ),
        migrations.AddField(
            model_name='databaserestore',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_restores', to=settings.AUTH_USER_MODEL, verbose_name='Tetikleyen Kullanıcı'),
        ),
        migrations.AddField(
            model_name='command',
            name='request_type',
            field=models.ForeignKey(blank=True, help_text='Alan-özel sınıflandırma (opsiyonel; örn. ministry_sample)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.requesttype', verbose_name='Talep Tipi'),
        ),
        migrations.AddField(
            model_name='scangroup',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_groups', to='api.connection', verbose_name='Bağlantı'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.connection', verbose_name='Bağlantı'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.parameter'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='scan_group',
            field=models.ForeignKey(blank=True, help_text="Set edilirse bu sensör, grup'un batch Modbus okumasından decode edilir (tek request, 100× hızlı). slave_id, function ve address grup ile uyumlu olmalı. Null ise sensör başına ayrı Modbus request atılır (legacy mod).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='api.scangroup', verbose_name='Scan Grubu'),
        ),
        migrations.AddField(
            model_name='readinghourly',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.sensor', verbose_name='Sensör'),
        ),
        migrations.AddField(
            model_name='readingfifteenmin',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.sensor', verbose_name='Sensör'),
        ),
        migrations.AddField(
            model_name='readingdaily',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.sensor', verbose_name='Sensör'),
        ),
        migrations.AddField(
            model_name='reading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.sensor', verbose_name='Sensör'),
        ),
        migrations.AddField(
            model_name='command',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='api.sensor', verbose_name='Hedef Sensör'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='api.sensor'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest', to='api.sensor', verbose_name='Sensör'),
        ),
        migrations.AddField(
            model_name='station',
            name='sample_request_sensor',
            field=models.ForeignKey(blank=True, help_text='StartSample servisinin tetikleyeceği dijital-out sensörü', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.sensor', verbose_name='Numune Alma Sensörü'),
        ),
        migrations.AddField(
            model_name='station',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poweroff',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_offs', to='api.station'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.station'),
        ),
        migrations.AddField(
            model_name='connection',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api.station', verbose_name='İstasyon'),
        ),
        migrations.AddField(
            model_name='station',
            name='station_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stationtype', verbose_name='İstasyon Tipi'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='last_saved_status',
            field=models.ForeignKey(blank=True, help_text='Reading tablosuna en son yazılan status. save_on_change modunda status değişimini de kayıt tetikleyicisi yapar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.statuscode', verbose_name='Son Kaydedilen Status'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statuscode', verbose_name='Status Kodu'),
        ),
        migrations.AddField(
            model_name='reading',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statuscode'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='api.station'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logtype'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['-created_at'], name='apilog_created_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['direction', '-created_at'], name='apilog_dir_created_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['url', 'response_status'], name='apilog_url_status_idx'),
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['tier', 'status', 'pruned', 'started_at'], name='backup_tier_idx'),
        ),
        migrations.AddConstraint(
            model_name='scangroup',
            constraint=models.UniqueConstraint(fields=('connection', 'name'), name='scan_group_unique_connection_name'),
        ),
        migrations.AddIndex(
            model_name='readinghourly',
            index=models.Index(fields=['sensor', '-bucket_start'], name='rhourly_sensor_bucket_idx'),
        ),
        migrations.AddConstraint(
            model_name='readinghourly',
            constraint=models.UniqueConstraint(fields=('sensor', 'bucket_start'), name='reading_hourly_unique_bucket'),
        ),
        migrations.AddIndex(
            model_name='readingfifteenmin',
            index=models.Index(fields=['sensor', '-bucket_start'], name='r15m_sensor_bucket_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingfifteenmin',
            constraint=models.UniqueConstraint(fields=('sensor', 'bucket_start'), name='reading_15m_unique_bucket'),
        ),
        migrations.AddIndex(
            model_name='readingdaily',
            index=models.Index(fields=['sensor', '-bucket_start'], name='rdaily_sensor_bucket_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingdaily',
            constraint=models.UniqueConstraint(fields=('sensor', 'bucket_start'), name='reading_daily_unique_bucket'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='cmd_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('station', 'name'), name='connection_unique_station_name'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['sensor', '-time_iso'], name='reading_sensor_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['time_iso', 'sensor'], name='reading_time_sensor_idx'),
        ),
    ]
