# Generated by Django 5.2.13 on 2026-06-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='decimals',
            field=models.IntegerField(blank=True, default=2, help_text='Kayıt öncesi kaç basamağa yuvarlanacak. Varsayılan 2. Boş bırakılırsa yuvarlama yapılmaz. Örn: 2 → 12.3456 → 12.35. Sadece sayısal (float/int) değerlere uygulanır.', null=True, verbose_name='Ondalık Hassasiyet'),
        ),
    ]
