# Generated by Django 5.0.6 on 2025-09-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_connections_alter_siminformation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='con_address',
            field=models.CharField(help_text='COM4 or 192.168.1.1', max_length=15, null=True, verbose_name='Bağlantı Adresi'),
        ),
    ]
