# Generated by Django 5.2.13 on 2026-04-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_sensor_decode_sensor_ascii_line_terminator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['station', 'name'], 'verbose_name_plural': 'Bağlantılar'},
        ),
        migrations.RemoveField(
            model_name='connection',
            name='communication_type',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='con_address',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='con_mode',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='con_name',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='con_type',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='status',
        ),
        migrations.AddField(
            model_name='connection',
            name='auto_reconnect',
            field=models.BooleanField(default=True, verbose_name='Otomatik Yeniden Bağlan'),
        ),
        migrations.AddField(
            model_name='connection',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='connection',
            name='host',
            field=models.CharField(blank=True, default='', help_text='Hostname veya IP (IPv4/IPv6); serial için boş', max_length=255, verbose_name='Host / IP'),
        ),
        migrations.AddField(
            model_name='connection',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Reader bu bağlantıyı tarasın mı?', verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Bağlantı Zamanı'),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Hata Zamanı'),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_error_message',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Son Hata Mesajı'),
        ),
        migrations.AddField(
            model_name='connection',
            name='name',
            field=models.CharField(default='', help_text='Bu istasyondaki bağlantının özgün adı', max_length=100, verbose_name='Bağlantı Adı'),
        ),
        migrations.AddField(
            model_name='connection',
            name='poll_interval_sec',
            field=models.IntegerField(default=10, help_text='Bu bağlantıdaki sensörlerin varsayılan okuma aralığı', verbose_name='Varsayılan Okuma Periyodu (sn)'),
        ),
        migrations.AddField(
            model_name='connection',
            name='protocol',
            field=models.CharField(choices=[('modbus_tcp', 'Modbus TCP'), ('modbus_rtu', 'Modbus RTU (Serial)'), ('modbus_ascii', 'Modbus ASCII (Serial)'), ('ascii_custom', 'Özel ASCII (Request-Response)')], default='modbus_tcp', max_length=20, verbose_name='Protokol'),
        ),
        migrations.AddField(
            model_name='connection',
            name='reconnect_delay_sec',
            field=models.IntegerField(default=5, verbose_name='Yeniden Bağlanma Gecikmesi (sn)'),
        ),
        migrations.AddField(
            model_name='connection',
            name='retry_count',
            field=models.IntegerField(default=1, verbose_name='Retry Sayısı'),
        ),
        migrations.AddField(
            model_name='connection',
            name='serial_port',
            field=models.CharField(blank=True, default='', help_text='COM4 (Windows) veya /dev/ttyUSB0 (Linux); TCP için boş', max_length=50, verbose_name='Serial Port'),
        ),
        migrations.AddField(
            model_name='connection',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api.station', verbose_name='İstasyon'),
        ),
        migrations.AddField(
            model_name='connection',
            name='timeout_ms',
            field=models.IntegerField(default=2000, verbose_name='Bağlantı Timeout (ms)'),
        ),
        migrations.AddField(
            model_name='connection',
            name='transport',
            field=models.CharField(choices=[('tcp', 'TCP/IP'), ('serial', 'Serial (RS-232/RS-485)')], default='tcp', max_length=10, verbose_name='Taşıma Katmanı'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='baudrate',
            field=models.IntegerField(blank=True, choices=[(300, '300'), (600, '600'), (1200, '1200'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (14400, '14400'), (19200, '19200'), (38400, '38400'), (57600, '57600'), (115200, '115200'), (230400, '230400'), (460800, '460800')], default=9600, null=True, verbose_name='Baudrate'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='byte_size',
            field=models.IntegerField(blank=True, choices=[(7, '7'), (8, '8')], default=8, null=True, verbose_name='Data Bits'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='dsrdtr',
            field=models.BooleanField(default=False, verbose_name='DSR/DTR'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='parity',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Odd'), (2, 'Even')], default=0, null=True, verbose_name='Parity'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='port',
            field=models.IntegerField(blank=True, default=502, help_text='Ağ portu (Modbus TCP: 502)', null=True, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='rtscts',
            field=models.BooleanField(default=False, verbose_name='RTS/CTS'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='stop_bits',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], default=1, null=True, verbose_name='Stop Bits'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='xonxoff',
            field=models.BooleanField(default=False, verbose_name='XON/XOFF'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('station', 'name'), name='connection_unique_station_name'),
        ),
    ]
