# Generated by Django 5.0.6 on 2025-09-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_connections_con_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_txt', models.CharField(max_length=50, null=True, verbose_name='Parametre Txt')),
                ('unit_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parametre ID')),
                ('sim_channel', models.CharField(max_length=250, null=True, verbose_name='Kanal ID')),
                ('gec_min', models.IntegerField(blank=True, null=True, verbose_name='Geçerli Veri Min')),
                ('gec_max', models.IntegerField(blank=True, null=True, verbose_name='Geçerli Veri Max')),
                ('olcum_min', models.IntegerField(blank=True, null=True, verbose_name='Ölçüm Altı')),
                ('olcum_max', models.IntegerField(blank=True, null=True, verbose_name='Ölçüm Üstü')),
            ],
            options={
                'verbose_name_plural': 'Sim Parametreleri',
                'db_table': 'sim_params',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_id', models.IntegerField(null=True, verbose_name='Kanal ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Parametre Adı')),
                ('unit', models.CharField(blank=True, max_length=150, null=True, verbose_name='Parametre Birim')),
                ('min_range', models.IntegerField(blank=True, null=True, verbose_name='Range Aralığı Min')),
                ('max_range', models.IntegerField(blank=True, null=True, verbose_name='Range Aralığı Min')),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.connections')),
                ('sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.simparams')),
            ],
            options={
                'verbose_name_plural': 'Parametreler',
                'db_table': 'sensors',
                'ordering': ['id'],
            },
        ),
    ]
