# Generated by Django 5.2.13 on 2026-04-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_connection_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteDevice',
        ),
    ]
