# Generated by Django 5.2.13 on 2026-06-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sensor_decimals'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Public IP')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='İlk görülme')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Son görülme')),
                ('is_current', models.BooleanField(default=True, verbose_name='Güncel')),
            ],
            options={
                'verbose_name': 'Public IP Kaydı',
                'verbose_name_plural': 'Public IP Kayıtları',
                'db_table': 'public_ip_record',
                'ordering': ['-last_seen'],
            },
        ),
    ]
