# Generated by Django 5.2.13 on 2026-06-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_publiciprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='display_order',
            field=models.IntegerField(db_index=True, default=0, help_text='Anasayfa canlı tablolarında artan sıra; eşitse alt kıstaslar uygulanır.', verbose_name='Görüntüleme Sırası'),
        ),
    ]
