# Generated by Django 5.2.13 on 2026-04-19 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_remotedevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(choices=[('bool', 'Bool (coil on/off)'), ('int', 'Integer'), ('float', 'Float'), ('string', 'ASCII metin')], default='int', max_length=10, verbose_name='Değer Tipi')),
                ('value', models.FloatField(blank=True, help_text='bool/int/float tipleri için (bool: 0/1)', null=True, verbose_name='Sayısal Değer')),
                ('value_text', models.CharField(blank=True, help_text="value_type='string' için gönderilecek ASCII komut", max_length=500, null=True, verbose_name='Metin Değeri')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('queued', 'Kuyruğa alındı'), ('executing', 'Yürütülüyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('timeout', 'Timeout'), ('expired', 'Süresi doldu'), ('cancelled', 'İptal')], default='pending', max_length=15, verbose_name='Durum')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='Deneme Sayısı')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='Max Deneme')),
                ('priority', models.IntegerField(default=100, help_text='Düşük sayı = yüksek öncelik (Unix nice stili). Örn: acil=10, normal=100, düşük=1000', verbose_name='Öncelik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Null → hemen çalıştırılır; değer → bu zamandan önce çalıştırılmaz', null=True, verbose_name='Planlı Zaman')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Bu zamandan sonra çalıştırılmamışsa 'expired' olarak işaretlenir", null=True, verbose_name='Geçerlilik Süresi')),
                ('executed_at', models.DateTimeField(blank=True, help_text='Yazma komutunun cihaza gönderildiği zaman', null=True, verbose_name='Yürütme Zamanı')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Başarı/başarısızlığın kesinleştiği zaman', null=True, verbose_name='Tamamlanma Zamanı')),
                ('source', models.CharField(choices=[('api', 'Dış API'), ('operator', 'Operatör'), ('scheduler', 'Zamanlayıcı'), ('rule', 'Kural Motoru'), ('system', 'Sistem')], default='api', max_length=15, verbose_name='Kaynak')),
                ('correlation_id', models.CharField(blank=True, help_text='Dış sistem trace / log ilişkilendirme kimliği', max_length=100, null=True, verbose_name='Correlation ID')),
                ('idempotency_key', models.CharField(blank=True, help_text='Aynı key ile gelen ikinci istek yeni komut oluşturmaz', max_length=100, null=True, unique=True, verbose_name='Idempotency Key')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='Hata Mesajı')),
                ('response_data', models.JSONField(blank=True, help_text='Cihaz yazma sonrası döndürdüğü değer/metadata (varsa)', null=True, verbose_name='Cihaz Yanıtı')),
                ('request_type', models.ForeignKey(blank=True, help_text='Alan-özel sınıflandırma (opsiyonel; örn. ministry_sample)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.requesttype', verbose_name='Talep Tipi')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden Kullanıcı')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='api.sensor', verbose_name='Hedef Sensör')),
            ],
            options={
                'verbose_name_plural': 'Komutlar',
                'db_table': 'command',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OutputRequest',
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='cmd_queue_idx'),
        ),
    ]
