# Generated by Django 5.0.6 on 2025-09-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_simparams_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationinfo',
            name='station_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Evsel Atıksu'), (2, 'Endüstriyel Atıksu'), (3, 'Kentsel Atıksu')], default=1, null=True),
        ),
    ]
