# Generated by Django 5.2.13 on 2026-06-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sensor_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='dashboard_hidden',
            field=models.BooleanField(default=False, help_text='True ise bu sensör dashboard anlık tablolarında (analog/dijital) gösterilmez. Polling, kayıt ve raporlar etkilenmez — yalnız görünürlük.', verbose_name="Dashboard'da Gizle"),
        ),
    ]
