# Generated by Django 5.0.6 on 2025-09-05 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_stationinfo_station_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=50, null=True, verbose_name='Parametre Adı')),
                ('parameter_txt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parametre Txt')),
                ('unit', models.CharField(blank=True, max_length=150, null=True, verbose_name='Parametre Birim')),
                ('unit_txt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parametre Txt')),
                ('channel_number', models.IntegerField(blank=True, null=True, verbose_name='Kanal No')),
                ('sim_channel', models.CharField(max_length=250, null=True, verbose_name='Kanal ID')),
                ('envi_channel', models.IntegerField(null=True, verbose_name='Envisoft Kanal ID')),
                ('gec_min', models.IntegerField(blank=True, null=True, verbose_name='Geçerli Veri Min')),
                ('gec_max', models.IntegerField(blank=True, null=True, verbose_name='Geçerli Veri Max')),
                ('olcum_min', models.IntegerField(blank=True, null=True, verbose_name='Ölçüm Altı')),
                ('olcum_max', models.IntegerField(blank=True, null=True, verbose_name='Ölçüm Üstü')),
                ('min_range', models.IntegerField(blank=True, null=True, verbose_name='Range Aralığı Min')),
                ('max_range', models.IntegerField(blank=True, null=True, verbose_name='Range Aralığı Min')),
            ],
            options={
                'verbose_name_plural': 'Parametreler',
                'db_table': 'parameters',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Status_Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True, verbose_name='Kod Numarası')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Status Kod Adı')),
            ],
            options={
                'verbose_name_plural': 'Status Kodları',
                'db_table': 'status_codes',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='sim',
        ),
        migrations.AlterModelOptions(
            name='sensors',
            options={'ordering': ['id'], 'verbose_name_plural': 'Sensors'},
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='ch_id',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='max_range',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='min_range',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='unit',
        ),
        migrations.AddField(
            model_name='sensors',
            name='address',
            field=models.IntegerField(blank=True, help_text='Modbus/Ascii Adresi/Sırası', null=True, verbose_name='Haberleşme Adresi'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='ascii_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ascii Kod'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sensör Marka'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='byte_order',
            field=models.CharField(choices=[('little', 'Endian.Little'), ('big', 'Endian.Big')], default='big', max_length=20, null=True, verbose_name='Byte Order'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='decode',
            field=models.CharField(blank=True, choices=[('float32', '32 Bit Float'), ('float64', '64 Bit Float'), ('hex', 'Hex'), (None, 'Raw Data')], default='float32', max_length=20, null=True, verbose_name='Decode'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='digital_inverse',
            field=models.BooleanField(default=False, verbose_name='Dijital Ters mi ?'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='factorA',
            field=models.FloatField(blank=True, default=1, help_text='result = ax+b', null=True, verbose_name='Kalibrasyon Faktörü (A)'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='factorB',
            field=models.FloatField(blank=True, default=0, help_text='result = ax+b', null=True, verbose_name='Kalibrasyon Faktörü (B)'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='function',
            field=models.IntegerField(blank=True, choices=[(1, 'Read Coils'), (2, 'Read Discrete Inputs'), (3, 'Read Holding Registers'), (4, 'Read Input Registers'), (5, 'Write Single Coil'), (6, 'Write Single Register'), (15, 'Write Multiple Coils'), (16, 'Write Multiple Registers')], default=3, null=True, verbose_name='Fonksiyon'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='instant',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Anlık Değer'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='is_random',
            field=models.BooleanField(default=False, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sensör Model'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='quantity',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Adres Aralığı'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='readtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Okuma Zamanı'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='send_status',
            field=models.BooleanField(default=False, verbose_name='Status Gönderilsin mi ?'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='sensor_type',
            field=models.IntegerField(choices=[(0, 'Analog Input'), (1, 'Analog Output'), (2, 'Dijital Input'), (3, 'Dijital Output')], default=0, null=True, verbose_name='Sensör Tipi'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='serial_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Seri No'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='signal_type',
            field=models.IntegerField(blank=True, choices=[(0, '4-20mA'), (1, '0-20mA'), (2, '0-10mV')], default=0, null=True, verbose_name='Sinyal Tipi'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='slave_id',
            field=models.IntegerField(default=1, null=True, verbose_name='Slave ID'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='word_order',
            field=models.CharField(choices=[('little', 'Endian.Little'), ('big', 'Endian.Big')], default='little', max_length=20, null=True, verbose_name='Word Order'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='con',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.connections', verbose_name='Bağlantı'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.parameters'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.status_codes'),
        ),
        migrations.DeleteModel(
            name='SimParams',
        ),
    ]
