# Generated by Django 5.2.13 on 2026-04-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_apilog_rebuild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
