# Generated by Django 5.0.6 on 2025-09-05 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_parameters_status_codes_remove_sensors_sim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='factorA',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='factorB',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='instant',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='is_random',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='readtime',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='send_status',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='status',
        ),
        migrations.CreateModel(
            name='SensorInstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.FloatField(blank=True, default=0, null=True, verbose_name='Anlık Değer')),
                ('readtime', models.DateTimeField(blank=True, null=True, verbose_name='Okuma Zamanı')),
                ('factorA', models.FloatField(blank=True, default=1, help_text='result = ax+b', null=True, verbose_name='Kalibrasyon Faktörü (A)')),
                ('factorB', models.FloatField(blank=True, default=0, help_text='result = ax+b', null=True, verbose_name='Kalibrasyon Faktörü (B)')),
                ('send_status', models.BooleanField(default=False, verbose_name='Status Gönderilsin mi ?')),
                ('is_random', models.BooleanField(default=False, verbose_name='Aktif')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sensors')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.status_codes')),
            ],
            options={
                'verbose_name_plural': 'Sensör Anlık Veriler',
                'db_table': 'sensor_instants',
                'ordering': ['channel'],
            },
        ),
    ]
