# Generated by Django 5.2.13 on 2026-06-12 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sensor_dashboard_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('body', models.TextField(verbose_name='Mesaj')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'E-posta'), ('both', 'Her ikisi')], default='both', max_length=10, verbose_name='Kanal')),
                ('category', models.CharField(blank=True, default='', max_length=60, verbose_name='Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Hazır Mesaj',
                'verbose_name_plural': 'Hazır Mesajlar',
                'db_table': 'message_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'E-posta')], max_length=10, verbose_name='Kanal')),
                ('recipient', models.CharField(max_length=255, verbose_name='Alıcı')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('ok', 'Başarılı'), ('fail', 'Hatalı')], max_length=8, verbose_name='Durum')),
                ('error', models.CharField(blank=True, default='', max_length=500, verbose_name='Hata')),
                ('kind', models.CharField(default='test', max_length=20, verbose_name='Tür')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Bildirim Kaydı',
                'verbose_name_plural': 'Bildirim Kayıtları',
                'db_table': 'notification_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='E-posta Etkin')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Sunucu')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='STARTTLS')),
                ('smtp_user', models.CharField(default='saisalarm57@gmail.com', max_length=255, verbose_name='SMTP Kullanıcı')),
                ('smtp_password', models.CharField(default='kyaqokitoascdyhq', max_length=255, verbose_name='SMTP Şifre')),
                ('mail_from', models.CharField(default='saisalarm57@gmail.com', max_length=255, verbose_name='Gönderen')),
                ('mail_subject', models.CharField(default='SAİS Mail Bildirim Servisi', max_length=255, verbose_name='Konu')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS Etkin')),
                ('netgsm_usercode', models.CharField(default='3129119605', max_length=64, verbose_name='NetGSM Kullanıcı Kodu')),
                ('netgsm_password', models.CharField(default='k1-c33mX', max_length=64, verbose_name='NetGSM Şifre')),
                ('netgsm_header', models.CharField(default='ONLNE CEVRE', max_length=32, verbose_name='NetGSM Başlık')),
                ('netgsm_api_url', models.CharField(default='https://api.netgsm.com.tr/sms/send/get/', max_length=255, verbose_name='NetGSM API URL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Bildirim Ayarı',
                'verbose_name_plural': 'Bildirim Ayarları',
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='StationAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.BooleanField(default=True, verbose_name='Bildirim Gönder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='api.station', verbose_name='İstasyon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_authorities', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İstasyon Yetkilisi',
                'verbose_name_plural': 'İstasyon Yetkilileri',
                'db_table': 'station_authority',
                'ordering': ['station_id', 'user_id'],
                'unique_together': {('station', 'user')},
            },
        ),
    ]
