# Generated by Django 5.2.13 on 2026-04-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_apilog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_start', models.DateTimeField(db_index=True, help_text="Aggregate periyodunun başlangıç zamanı (bucket'a yuvarlanmış)", verbose_name='Bucket Başlangıcı')),
                ('avg_value', models.FloatField(blank=True, null=True, verbose_name='Ortalama')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max')),
                ('count', models.IntegerField(default=0, verbose_name='Toplam Okuma')),
                ('bad_count', models.IntegerField(default=0, verbose_name='Bad Kalite Sayısı')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Hesaplanma Zamanı')),
            ],
            options={
                'verbose_name_plural': 'Günlük Aggregate',
                'db_table': 'reading_daily',
                'ordering': ['-bucket_start', 'sensor'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingFifteenMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_start', models.DateTimeField(db_index=True, help_text="Aggregate periyodunun başlangıç zamanı (bucket'a yuvarlanmış)", verbose_name='Bucket Başlangıcı')),
                ('avg_value', models.FloatField(blank=True, null=True, verbose_name='Ortalama')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max')),
                ('count', models.IntegerField(default=0, verbose_name='Toplam Okuma')),
                ('bad_count', models.IntegerField(default=0, verbose_name='Bad Kalite Sayısı')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Hesaplanma Zamanı')),
            ],
            options={
                'verbose_name_plural': '15 Dakikalık Aggregate',
                'db_table': 'reading_15m',
                'ordering': ['-bucket_start', 'sensor'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_start', models.DateTimeField(db_index=True, help_text="Aggregate periyodunun başlangıç zamanı (bucket'a yuvarlanmış)", verbose_name='Bucket Başlangıcı')),
                ('avg_value', models.FloatField(blank=True, null=True, verbose_name='Ortalama')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max')),
                ('count', models.IntegerField(default=0, verbose_name='Toplam Okuma')),
                ('bad_count', models.IntegerField(default=0, verbose_name='Bad Kalite Sayısı')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Hesaplanma Zamanı')),
            ],
            options={
                'verbose_name_plural': 'Saatlik Aggregate',
                'db_table': 'reading_hourly',
                'ordering': ['-bucket_start', 'sensor'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sensorlatest',
            options={'ordering': ['sensor'], 'verbose_name_plural': 'Sensör Anlık Snapshot'},
        ),
        migrations.RemoveField(
            model_name='sensorlatest',
            name='factorA',
        ),
        migrations.RemoveField(
            model_name='sensorlatest',
            name='factorB',
        ),
        migrations.RemoveField(
            model_name='sensorlatest',
            name='instant',
        ),
        migrations.RemoveField(
            model_name='sensorlatest',
            name='is_random',
        ),
        migrations.RemoveField(
            model_name='sensorlatest',
            name='send_status',
        ),
        migrations.AddField(
            model_name='reading',
            name='origin',
            field=models.CharField(choices=[('polled', 'Polled (cihazdan okundu)'), ('manual', 'Manual (operatör girişi)'), ('calculated', 'Calculated (hesaplanmış)'), ('simulated', 'Simulated (rastgele/test)'), ('interpolated', 'Interpolated (eksik veri dolduruldu)')], default='polled', max_length=15, verbose_name='Veri Kaynağı'),
        ),
        migrations.AddField(
            model_name='reading',
            name='quality',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('uncertain', 'Uncertain'), ('stale', 'Stale'), ('substituted', 'Substituted'), ('manual', 'Manual')], default='good', max_length=15, verbose_name='Kalite'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='is_simulated',
            field=models.BooleanField(default=False, help_text='True ise reader cihazdan değer okumak yerine rastgele üretir (test/demo için)', verbose_name='Simülasyon Modu'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='report_status',
            field=models.BooleanField(default=False, help_text="True ise bu sensörün status'ü dış sisteme (Bakanlık) gönderilir", verbose_name='Status Raporla'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='last_change_at',
            field=models.DateTimeField(blank=True, help_text='Değer en son ne zaman bir önceki okumadan farklıydı (deadband/COV için)', null=True, verbose_name='Son Değişim Zamanı'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='quality',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('uncertain', 'Uncertain'), ('stale', 'Stale'), ('substituted', 'Substituted'), ('manual', 'Manual')], default='good', help_text='Anlık değerin güvenilirlik düzeyi', max_length=15, verbose_name='Kalite'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='update_count',
            field=models.BigIntegerField(default=0, help_text='Bu sensör için kaç okuma yapıldı (debug/health monitor)', verbose_name='Güncelleme Sayısı'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='value',
            field=models.FloatField(blank=True, default=0, help_text='scale/offset uygulanmış mühendislik değeri', null=True, verbose_name='Anlık Değer'),
        ),
        migrations.AlterField(
            model_name='sensorlatest',
            name='readtime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Okuma Zamanı'),
        ),
        migrations.AlterField(
            model_name='sensorlatest',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest', to='api.sensor', verbose_name='Sensör'),
        ),
        migrations.AlterField(
            model_name='sensorlatest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statuscode', verbose_name='Status Kodu'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['sensor', '-time_iso'], name='reading_sensor_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['time_iso', 'sensor'], name='reading_time_sensor_idx'),
        ),
        migrations.AddField(
            model_name='readingdaily',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.sensor', verbose_name='Sensör'),
        ),
        migrations.AddField(
            model_name='readingfifteenmin',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.sensor', verbose_name='Sensör'),
        ),
        migrations.AddField(
            model_name='readinghourly',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.sensor', verbose_name='Sensör'),
        ),
        migrations.AddIndex(
            model_name='readingdaily',
            index=models.Index(fields=['sensor', '-bucket_start'], name='rdaily_sensor_bucket_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingdaily',
            constraint=models.UniqueConstraint(fields=('sensor', 'bucket_start'), name='reading_daily_unique_bucket'),
        ),
        migrations.AddIndex(
            model_name='readingfifteenmin',
            index=models.Index(fields=['sensor', '-bucket_start'], name='r15m_sensor_bucket_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingfifteenmin',
            constraint=models.UniqueConstraint(fields=('sensor', 'bucket_start'), name='reading_15m_unique_bucket'),
        ),
        migrations.AddIndex(
            model_name='readinghourly',
            index=models.Index(fields=['sensor', '-bucket_start'], name='rhourly_sensor_bucket_idx'),
        ),
        migrations.AddConstraint(
            model_name='readinghourly',
            constraint=models.UniqueConstraint(fields=('sensor', 'bucket_start'), name='reading_hourly_unique_bucket'),
        ),
    ]
