# Generated by Django 5.0.6 on 2025-09-05 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_sensors_factora_remove_sensors_factorb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorinstants',
            name='channel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sensors'),
        ),
    ]
