# Generated by Django 5.2.13 on 2026-06-12 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_messagetemplate_notificationlog_notificationsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('analog', 'Ölçüm (Analog Limit)'), ('digital', 'Diagnostik (Dijital Kanal)'), ('offline', 'İstasyon Offline')], default='analog', max_length=10, verbose_name='Alarm Türü')),
                ('condition', models.CharField(blank=True, choices=[('min', 'Limit Altı'), ('max', 'Limit Üstü'), ('minmax', 'Limit Altı ve Üstü')], default='', max_length=10, verbose_name='Limit Tipi')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min Değer')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max Değer')),
                ('offline_seconds', models.IntegerField(default=900, help_text='Son veriden bu kadar saniye geçtiyse istasyon offline sayılır.', verbose_name='Offline Eşiği (sn)')),
                ('period_minutes', models.IntegerField(choices=[(15, '15 Dakika'), (30, '30 Dakika'), (60, 'Saat Başı'), (180, '3 Saat'), (360, '6 Saat'), (720, '12 Saat'), (1440, 'Günlük')], default=60, help_text='Aynı alarm için iki bildirim arası minimum süre.', verbose_name='Alarm Periyodu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('notify_all', models.BooleanField(default=True, help_text='True ise tüm aktif kullanıcılara; False ise yalnız oluşturana gönderilir.', verbose_name='Tüm Yetkililer')),
                ('send_sms', models.BooleanField(default=True, verbose_name='SMS Gönder')),
                ('send_email', models.BooleanField(default=True, verbose_name='E-posta Gönder')),
                ('enabled', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Tetiklenme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.parameter', verbose_name='Kanal (Parametre)')),
                ('sensor', models.ForeignKey(blank=True, help_text='Aktif (1) olduğunda alarm üreten dijital input sensörü.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.sensor', verbose_name='Dijital Kanal')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_rules', to='api.station', verbose_name='İstasyon')),
                ('trigger_output', models.ForeignKey(blank=True, help_text='Alarm tetiklendiğinde 1 yazılacak dijital output sensörü (opsiyonel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.sensor', verbose_name='Tetiklenecek Output')),
            ],
            options={
                'verbose_name': 'Alarm Tanımı',
                'verbose_name_plural': 'Alarm Tanımları',
                'db_table': 'alarm_rule',
                'ordering': ['-created_at'],
            },
        ),
    ]
