# Generated by Django 5.2.13 on 2026-06-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alarmrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmrule',
            name='trigger_output',
        ),
    ]
