# Generated by Django 5.0.6 on 2025-09-05 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sensorinstants_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Status Kod Adı')),
            ],
            options={
                'verbose_name_plural': 'Log Tipleri',
                'db_table': 'log_types',
            },
        ),
        migrations.CreateModel(
            name='Sample_Senario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_ort', models.FloatField(null=True, verbose_name='Ph Ort.')),
                ('akm_ort', models.FloatField(null=True, verbose_name='Akm Ort.')),
                ('koi_ort', models.FloatField(null=True, verbose_name='Koi Ort.')),
                ('alarm_adet', models.IntegerField(blank=True, null=True, verbose_name='Alarm Adet')),
                ('alarm_durum', models.BooleanField(blank=True, default=False, null=True, verbose_name='Alarm Durumu')),
                ('alarm_param', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alarm Parametre')),
                ('alarm_msg', models.CharField(blank=True, max_length=250, null=True, verbose_name='Alarm Mesajı')),
                ('time_iso', models.DateTimeField(auto_now=True, null=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Numune Alma Canlı',
                'db_table': 'sample_senaris',
                'ordering': ['-time_iso'],
            },
        ),
        migrations.CreateModel(
            name='Sim_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_v', models.FloatField(blank=True, null=True, verbose_name='Ph Anlık')),
                ('ph_s', models.IntegerField(blank=True, null=True, verbose_name='Ph Status')),
                ('il_v', models.FloatField(blank=True, null=True, verbose_name='İletkenlik Anlık')),
                ('il_s', models.IntegerField(blank=True, null=True, verbose_name='İletkenlik Status')),
                ('coz_v', models.FloatField(blank=True, null=True, verbose_name='Çöz. Oks. Anlık')),
                ('coz_s', models.IntegerField(blank=True, null=True, verbose_name='Çöz. Oks. Status')),
                ('debi_v', models.FloatField(blank=True, null=True, verbose_name='Debi Anlık')),
                ('debi_s', models.IntegerField(blank=True, null=True, verbose_name='Debi Status')),
                ('sic_v', models.FloatField(blank=True, null=True, verbose_name='Sıcaklık Anlık')),
                ('sic_s', models.IntegerField(blank=True, null=True, verbose_name='Sıcaklık Status')),
                ('akis_v', models.FloatField(blank=True, null=True, verbose_name='Akış Hızı Anlık')),
                ('akis_s', models.IntegerField(blank=True, null=True, verbose_name='Akış Hızı Status')),
                ('koi_v', models.FloatField(blank=True, null=True, verbose_name='Koi Anlık')),
                ('koi_s', models.IntegerField(blank=True, null=True, verbose_name='Koi Status')),
                ('akm_v', models.FloatField(blank=True, null=True, verbose_name='Akm Anlık')),
                ('akm_s', models.IntegerField(blank=True, null=True, verbose_name='Akm Status')),
                ('time_iso', models.DateTimeField(auto_now=True, null=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Sim Verileri',
                'db_table': 'sim_data',
                'ordering': ['-time_iso'],
            },
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Zero'), (1, 'Span'), (2, 'Multi')], null=True, verbose_name='Kalibrasyon Tipi')),
                ('period', models.IntegerField(default=60, null=True, verbose_name='Kalibrasyon Periyodu')),
                ('cal_ref', models.FloatField(null=True, verbose_name='Referans Değer')),
                ('cal_average', models.FloatField(null=True, verbose_name='Ortalama Değer')),
                ('cal_std', models.FloatField(null=True, verbose_name='Standart Sapma')),
                ('is_valid', models.BooleanField(null=True, verbose_name='Geçerli mi ?')),
                ('time_iso', models.DateTimeField(auto_now=True, verbose_name='Kayıt Tarihi')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sensors')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kalibrasyon Kayıtları',
                'db_table': 'calibration',
                'ordering': ['-time_iso'],
            },
        ),
        migrations.CreateModel(
            name='Api_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Request Url')),
                ('data', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Request Data')),
                ('header', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Request Header')),
                ('param', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Request Param')),
                ('token', models.CharField(blank=True, max_length=250, null=True, verbose_name='Token')),
                ('response', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Response')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='Status Kod')),
                ('time_iso', models.DateTimeField(auto_now=True, null=True, verbose_name='Kayıt Tarihi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.log_types')),
            ],
            options={
                'verbose_name_plural': 'Api Log Kayıtları',
                'db_table': 'api_log',
                'ordering': ['-time_iso'],
            },
        ),
        migrations.CreateModel(
            name='Poweroff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Bitiş Tarihi')),
                ('time_iso', models.DateTimeField(auto_now=True, verbose_name='Kayıt Tarihi')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stationinfo')),
            ],
            options={
                'verbose_name_plural': 'Poweroff Kayıtları',
                'db_table': 'poweroff',
                'ordering': ['-time_iso'],
            },
        ),
        migrations.CreateModel(
            name='Reads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True, verbose_name='Değer')),
                ('time_iso', models.DateTimeField(null=True, verbose_name='Kayıt Tarihi')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sensors', verbose_name='Kanal')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.status_codes')),
            ],
            options={
                'verbose_name_plural': 'Reads',
                'db_table': 'reads',
                'ordering': ['-time_iso'],
            },
        ),
        migrations.CreateModel(
            name='Sys_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True, verbose_name='Açıklama')),
                ('time_iso', models.DateTimeField(auto_now=True, verbose_name='Kayıt Tarihi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.log_types')),
            ],
            options={
                'verbose_name_plural': 'Sistem Log Kayıtları',
                'db_table': 'sys_log',
                'ordering': ['-time_iso'],
            },
        ),
    ]
