# Generated by Django 5.2.13 on 2026-04-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_readingdaily_readingfifteenmin_readinghourly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Bu bağlantı için son polling girişiminin zamanı (başarı/başarısızlık fark etmez). dispatch_polls due-check için kullanır.', null=True, verbose_name='Son Polling Zamanı'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='last_connected_at',
            field=models.DateTimeField(blank=True, help_text='Son başarılı bağlantı zamanı.', null=True, verbose_name='Son Bağlantı Zamanı'),
        ),
    ]
