# Generated by Django 5.2.13 on 2026-06-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_alarmrule_trigger_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmrule',
            name='trigger_state',
            field=models.BooleanField(default=True, help_text='True = sensör Aktif (ON) olunca; False = Pasif (OFF) olunca alarm.', verbose_name='Tetikleme Durumu'),
        ),
        migrations.AlterField(
            model_name='alarmrule',
            name='sensor',
            field=models.ForeignKey(blank=True, help_text='Durumu seçilen değere geçtiğinde alarm üreten dijital sensör (DI/DO).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.sensor', verbose_name='Dijital Sensör'),
        ),
    ]
