# Generated by Django 5.0.6 on 2025-09-29 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_log_types_sample_senario_sim_data_calibration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.stationinfo'),
        ),
    ]
