# Generated by Django 5.2.13 on 2026-04-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_connection_last_polled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='protocol',
            field=models.CharField(choices=[('modbus_tcp', 'Modbus TCP'), ('modbus_rtu', 'Modbus RTU (Serial)'), ('modbus_ascii', 'Modbus ASCII (Serial)'), ('modbus_rtu_over_tcp', 'Modbus RTU over TCP (Gateway)'), ('modbus_ascii_over_tcp', 'Modbus ASCII over TCP (Gateway)'), ('ascii_custom', 'Özel ASCII (Request-Response)')], default='modbus_tcp', max_length=30, verbose_name='Protokol'),
        ),
    ]
