# Generated by Django 5.2.13 on 2026-04-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_connection_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='save_interval_sec',
            field=models.IntegerField(blank=True, help_text="Reading tablosuna ne sıklıkta yazılacak. Null = her okumada Reading insert. Örn: poll=5sn, save=60sn ise anlık değer 5 sn'de bir güncellenir ama tarihsel veri dakikada 1 yazılır (DB tasarrufu).", null=True, verbose_name='Kayıt Periyodu (sn)'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='decimals',
            field=models.IntegerField(blank=True, help_text='Kayıt öncesi kaç basamağa yuvarlanacak. None = yuvarlama yok. Örn: 2 → 12.3456 → 12.35. Sadece sayısal (float/int) değerlere uygulanır.', null=True, verbose_name='Ondalık Hassasiyet'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='last_saved_at',
            field=models.DateTimeField(blank=True, help_text='Reading tablosuna son insert zamanı. Connection.save_interval_sec için kullanılır.', null=True, verbose_name='Son Reading Kayıt Zamanı'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='poll_interval_sec',
            field=models.IntegerField(default=10, help_text='Cihaza ne sıklıkta bağlanıp okuma yapılacak. Snapshot (SensorLatest) her okumada güncellenir.', verbose_name='Okuma Periyodu (sn)'),
        ),
    ]
