# Generated by Django 5.0.6 on 2025-09-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_parameters_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.stationinfo'),
        ),
    ]
