# Generated by Django 5.2.13 on 2026-06-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alarmrule_trigger_state_alter_alarmrule_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingFiveMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_start', models.DateTimeField(db_index=True, help_text="Aggregate periyodunun başlangıç zamanı (bucket'a yuvarlanmış)", verbose_name='Bucket Başlangıcı')),
                ('avg_value', models.FloatField(blank=True, null=True, verbose_name='Ortalama')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max')),
                ('count', models.IntegerField(default=0, verbose_name='Toplam Okuma')),
                ('bad_count', models.IntegerField(default=0, verbose_name='Bad Kalite Sayısı')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Hesaplanma Zamanı')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.sensor', verbose_name='Sensör')),
            ],
            options={
                'verbose_name_plural': '5 Dakikalık Aggregate',
                'db_table': 'reading_five_min',
                'ordering': ['-bucket_start', 'sensor'],
                'abstract': False,
                'indexes': [models.Index(fields=['sensor', '-bucket_start'], name='r5m_sensor_bucket_idx')],
                'constraints': [models.UniqueConstraint(fields=('sensor', 'bucket_start'), name='reading_5m_unique_bucket')],
            },
        ),
    ]
