# Generated by Django 5.2.13 on 2026-06-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_readingfivemin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(verbose_name='Son Canlılık')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
            ],
            options={
                'verbose_name': 'Sistem Canlılık',
                'verbose_name_plural': 'Sistem Canlılık',
                'db_table': 'system_heartbeat',
            },
        ),
    ]
