# Generated by Django 5.0.6 on 2025-09-29 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_parameters_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='sys_log',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stationinfo'),
        ),
    ]
