# Generated by Django 5.2.13 on 2026-04-22 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_connection_save_interval_sec_sensor_decimals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Açıklayıcı isim (örn. 'Analog girişler 0-20', 'Status bitleri 100-150')", max_length=100, verbose_name='Grup Adı')),
                ('slave_id', models.IntegerField(default=1, verbose_name='Slave ID')),
                ('function', models.IntegerField(choices=[(1, 'Read Coils'), (2, 'Read Discrete Inputs'), (3, 'Read Holding Registers'), (4, 'Read Input Registers')], default=3, verbose_name='Fonksiyon')),
                ('start_address', models.IntegerField(help_text='Modbus register başlangıç adresi (0-tabanlı)', verbose_name='Başlangıç Adresi')),
                ('quantity', models.IntegerField(help_text='Okunacak register/coil sayısı. Max: function 3/4 → 125, function 1/2 → 2000', verbose_name='Register Sayısı')),
                ('is_active', models.BooleanField(default=True, help_text="False ise bu grup polling'de atlanır", verbose_name='Aktif')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_groups', to='api.connection', verbose_name='Bağlantı')),
            ],
            options={
                'verbose_name_plural': 'Scan Grupları',
                'db_table': 'scan_group',
                'ordering': ['connection', 'slave_id', 'start_address'],
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='scan_group',
            field=models.ForeignKey(blank=True, help_text="Set edilirse bu sensör, grup'un batch Modbus okumasından decode edilir (tek request, 100× hızlı). slave_id, function ve address grup ile uyumlu olmalı. Null ise sensör başına ayrı Modbus request atılır (legacy mod).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='api.scangroup', verbose_name='Scan Grubu'),
        ),
        migrations.AddConstraint(
            model_name='scangroup',
            constraint=models.UniqueConstraint(fields=('connection', 'name'), name='scan_group_unique_connection_name'),
        ),
    ]
