# Generated by Django 5.2.13 on 2026-04-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_scangroup_sensor_scan_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='data_type',
            field=models.CharField(blank=True, choices=[('int16', 'Int16 / Short (signed, 1 register)'), ('uint16', 'UInt16 / Word (unsigned, 1 register)'), ('int32', 'Int32 / DInt (signed, 2 register)'), ('uint32', 'UInt32 / DWord (unsigned, 2 register)'), ('int64', 'Int64 / LInt (signed, 4 register)'), ('uint64', 'UInt64 / LWord (unsigned, 4 register)'), ('float32', 'Float32 / Real / Float (IEEE-754, 2 register)'), ('float64', 'Float64 / Double / LReal (IEEE-754, 4 register)'), ('bool', 'Bool (coil / 1-bit)'), ('bit', 'Bit (register içinden bit_position)'), ('string', 'String (ASCII metin)'), ('raw', 'Raw bytes')], default='float32', help_text="Raw byte/register'ların nasıl yorumlanacağı", max_length=20, null=True, verbose_name='Veri Tipi'),
        ),
    ]
