# Generated by Django 5.0.6 on 2025-09-29 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sys_log_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_log',
            name='station',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stationinfo'),
        ),
    ]
