# Generated by Django 5.2.13 on 2026-06-12 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_systemheartbeat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Başlık')),
                ('note', models.TextField(blank=True, default='', verbose_name='Not')),
                ('remind_at', models.DateTimeField(verbose_name='Hatırlatma Zamanı')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek')], default='normal', max_length=10, verbose_name='Öncelik')),
                ('is_done', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Tamamlayan')),
                ('station', models.ForeignKey(blank=True, help_text='İsteğe bağlı — hatırlatıcıyı bir istasyona bağla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='api.station', verbose_name='İstasyon')),
            ],
            options={
                'verbose_name': 'Hatırlatıcı',
                'verbose_name_plural': 'Hatırlatıcılar',
                'db_table': 'reminder',
                'ordering': ['remind_at'],
                'indexes': [models.Index(fields=['remind_at', 'is_done'], name='reminder_remind__90e731_idx')],
            },
        ),
    ]
