# Generated by Django 5.2.13 on 2026-06-08 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_sensor_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='cov_heartbeat_sec',
            field=models.IntegerField(blank=True, help_text="save_on_change=True iken değer değişmese bile en geç bu sürede bir kayıt yapılır (historian'da sonsuz boşluk oluşmasın). None = heartbeat yok, değişene kadar hiç yazılmaz.", null=True, verbose_name='Heartbeat (sn)'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='deadband',
            field=models.FloatField(blank=True, help_text='save_on_change=True iken analog için son KAYDEDİLEN değere göre izin verilen sapma (mühendislik birimi, mutlak). |yeni - son_kayıt| > deadband ise kayıt yapılır. None/0 = her farklı değer kaydedilir. Bool/dijital sensörlerde göz ardı edilir (her değişim kaydedilir).', null=True, verbose_name='Ölü Bant (deadband)'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='save_on_change',
            field=models.BooleanField(default=False, help_text="True ise Reading sadece değer değiştiğinde (analogda deadband'i aşan değişim, dijitalde herhangi bir değişim) ya da status değiştiğinde yazılır. SensorLatest snapshot'ı yine her okumada güncellenir (HMI taze kalır). Connection.save_interval_sec minimum aralık olarak yine uygulanır.", verbose_name='Sadece Değişimde Kaydet'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='last_saved_status',
            field=models.ForeignKey(blank=True, help_text='Reading tablosuna en son yazılan status. save_on_change modunda status değişimini de kayıt tetikleyicisi yapar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.statuscode', verbose_name='Son Kaydedilen Status'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='last_saved_value',
            field=models.FloatField(blank=True, help_text="Reading tablosuna en son yazılan değer. save_on_change (deadband) karşılaştırmasının referansı — anlık değil son KAYIT değeridir (yavaş drift'in birikip tetiklemesi için).", null=True, verbose_name='Son Kaydedilen Değer'),
        ),
    ]
