# Generated by Django 5.2.13 on 2026-06-13 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='severity',
            field=models.CharField(choices=[('info', 'Bilgi'), ('warning', 'Uyarı'), ('critical', 'Kritik')], db_index=True, default='info', max_length=10, verbose_name='Önem Derecesi'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='username',
            field=models.CharField(blank=True, help_text='Olay anındaki kullanıcı adı (kullanıcı silinse/başarısız girişte de korunur).', max_length=150, null=True, verbose_name='Kullanıcı Adı'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='time_iso',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Kayıt Tarihi'),
        ),
    ]
