# Generated by Django 5.0.6 on 2025-09-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_sys_log_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Out_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Değer')),
                ('alarm_level', models.IntegerField(choices=[(1, 'Bakanlık Numune Talebi'), (2, 'Operatör Talebi'), (2, 'Otomatik Numune Senaryosu')], verbose_name='Alarm Level')),
                ('is_completed', models.BooleanField(default=False)),
                ('request_code', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Kayıt Tarihi')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensors')),
            ],
            options={
                'verbose_name_plural': 'Dijital Out Talepleri',
                'db_table': 'out_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Sample_Senario',
        ),
        migrations.DeleteModel(
            name='Sim_Data',
        ),
    ]
