# Generated by Django 5.2.13 on 2026-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_systemlog_event_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sim_max',
            field=models.FloatField(blank=True, help_text='Simülasyon modunda üretilecek rastgele değerin üst sınırı. Boşsa parametrenin max_range değeri (o da yoksa 100) kullanılır.', null=True, verbose_name='Simülasyon Max'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sim_min',
            field=models.FloatField(blank=True, help_text='Simülasyon modunda üretilecek rastgele değerin alt sınırı. Boşsa parametrenin min_range değeri (o da yoksa 0) kullanılır.', null=True, verbose_name='Simülasyon Min'),
        ),
    ]
