# Generated by Django 5.2.13 on 2026-06-08 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sensor_cov_heartbeat_sec_sensor_deadband_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('yearly', 'Yıllık'), ('manual', 'Manuel')], max_length=10, unique=True, verbose_name='Periyot')),
                ('enabled', models.BooleanField(default=True, help_text='Kapalıysa bu periyotta otomatik yedek alınmaz.', verbose_name='Aktif')),
                ('retention', models.PositiveIntegerField(default=7, help_text='Bu periyotta tutulacak yedek dosyası sayısı; fazlası silinir.', verbose_name='Saklanacak Adet')),
            ],
            options={
                'verbose_name': 'Yedekleme Politikası',
                'verbose_name_plural': 'Yedekleme Politikaları',
                'db_table': 'backup_policy',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('yearly', 'Yıllık'), ('manual', 'Manuel')], max_length=10, verbose_name='Periyot')),
                ('filename', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('path', models.CharField(max_length=500, verbose_name='Tam Yol')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Boyut (byte)')),
                ('status', models.CharField(choices=[('running', 'Alınıyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], default='running', max_length=10, verbose_name='Durum')),
                ('db_name', models.CharField(max_length=128, verbose_name='Veritabanı')),
                ('app_version', models.CharField(default='dev', help_text='Yedek alındığı andaki APP_VERSION.', max_length=50, verbose_name='Uygulama Sürümü')),
                ('migration_state', models.JSONField(blank=True, help_text='{app: son_uygulanan_migration} — geri yüklemede şema uyumu için.', null=True, verbose_name='Migration Durumu')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('error', models.TextField(blank=True, default='', verbose_name='Hata')),
                ('trigger', models.CharField(choices=[('auto', 'Otomatik'), ('manual', 'Manuel')], default='auto', max_length=10, verbose_name='Tetikleyici')),
                ('pruned', models.BooleanField(default=False, help_text='Retention politikası gereği .bak dosyası silindi (kayıt audit için kalır).', verbose_name='Dosya Silindi')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_backups', to=settings.AUTH_USER_MODEL, verbose_name='Tetikleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Veritabanı Yedeği',
                'verbose_name_plural': 'Veritabanı Yedekleri',
                'db_table': 'database_backup',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseRestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255, verbose_name='Kaynak Dosya')),
                ('status', models.CharField(choices=[('running', 'Yükleniyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], default='running', max_length=10, verbose_name='Durum')),
                ('compatibility', models.CharField(choices=[('exact', 'Birebir'), ('forward', 'İleri Migrate'), ('block', 'Engellendi'), ('forced', 'Zorlandı')], max_length=10, verbose_name='Uyumluluk')),
                ('ran_migrate', models.BooleanField(default=False, verbose_name='Migrate Çalıştı')),
                ('app_version_at_backup', models.CharField(blank=True, default='', max_length=50, verbose_name='Yedek Sürümü')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('error', models.TextField(blank=True, default='', verbose_name='Hata')),
                ('source_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='api.databasebackup', verbose_name='Kaynak Yedek')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_restores', to=settings.AUTH_USER_MODEL, verbose_name='Tetikleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Veritabanı Geri Yükleme',
                'verbose_name_plural': 'Veritabanı Geri Yüklemeler',
                'db_table': 'database_restore',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['tier', 'status', 'pruned', 'started_at'], name='backup_tier_idx'),
        ),
    ]
