# Generated by Django 5.0.6 on 2025-09-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_out_requests_delete_sample_senario_delete_sim_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='sensor',
            new_name='parameters',
        ),
    ]
