# Generated by Django 5.2.13 on 2026-06-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_backuppolicy_databasebackup_databaserestore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(blank=True, default='', max_length=120, verbose_name='Lisans Anahtarı')),
                ('customer', models.CharField(blank=True, default='', max_length=200, verbose_name='Müşteri')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Bitişi')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Veriliş Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Doldu'), ('invalid', 'Geçersiz'), ('missing', 'Lisans Yok')], default='missing', max_length=10, verbose_name='Durum')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='İmza Geçerli')),
                ('raw_token', models.JSONField(blank=True, help_text="Doğrulanmış son token (restart/offline'da yeniden doğrulanır).", null=True, verbose_name='İmzalı Token')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Kontrol')),
                ('last_check_ok', models.BooleanField(default=False, verbose_name='Son Kontrol Başarılı')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Son Hata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İlk Kayıt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
            ],
            options={
                'verbose_name': 'Lisans',
                'verbose_name_plural': 'Lisans',
                'db_table': 'license',
            },
        ),
    ]
