# Generated by Django 5.2.13 on 2026-06-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sensor_sim_max_sensor_sim_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasebackup',
            name='pruned',
            field=models.BooleanField(default=False, help_text='Retention politikası gereği .dump dosyası silindi (kayıt audit için kalır).', verbose_name='Dosya Silindi'),
        ),
    ]
