# Generated by Django 5.2.13 on 2026-06-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_databasebackup_pruned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='save_on_change',
            field=models.BooleanField(blank=True, default=None, help_text="True ise Reading sadece değer değiştiğinde (analogda deadband'i aşan değişim, dijitalde herhangi bir değişim) ya da status değiştiğinde yazılır. SensorLatest snapshot'ı yine her okumada güncellenir (HMI taze kalır). Connection.save_interval_sec minimum aralık olarak yine uygulanır. Boş (None) bırakılırsa oluşturmada tipe göre varsayılan uygulanır: dijital (DI/DO) için açık, analog için kapalı. Açıkça True/False seçilirse o değer korunur.", null=True, verbose_name='Sadece Değişimde Kaydet'),
        ),
    ]
