# Generated by Django 5.2.13 on 2026-06-08 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text="Kapalıyken Caddy güvenli internal (self-signed) fallback'e düşer.", verbose_name='Etkin')),
                ('domain', models.CharField(blank=True, default='', help_text='Örn. sais-tesis1.envisoft.com.tr (DNS A kaydı + 443 yönlendirme gerekir).', max_length=253, verbose_name='Domain')),
                ('tls_mode', models.CharField(choices=[('letsencrypt', "Let's Encrypt (otomatik)"), ('manual', 'Manuel Sertifika (PEM/PFX)'), ('internal', 'Self-Signed (LAN/test)')], default='internal', max_length=12, verbose_name='TLS Modu')),
                ('http_redirect', models.BooleanField(default=True, verbose_name='HTTP→HTTPS Yönlendir')),
                ('letsencrypt_email', models.EmailField(blank=True, default='', help_text='ACME bildirimleri için; letsencrypt modunda zorunlu.', max_length=254, verbose_name="Let's Encrypt E-postası")),
                ('manual_cert_pem', models.TextField(blank=True, default='', verbose_name='Sertifika PEM (zincir dahil)')),
                ('manual_key_pem', models.TextField(blank=True, default='', verbose_name='Özel Anahtar PEM (şifresiz)')),
                ('manual_cert_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Sertifika Yükleme Tarihi')),
                ('manual_cert_subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Sertifika Sahibi (CN)')),
                ('manual_cert_not_after', models.DateTimeField(blank=True, null=True, verbose_name='Sertifika Bitiş Tarihi')),
                ('last_rendered_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Üretim')),
                ('last_render_error', models.TextField(blank=True, default='', verbose_name='Son Üretim Hatası')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı')),
            ],
            options={
                'verbose_name': 'Web Erişim Ayarı',
                'verbose_name_plural': 'Web Erişim Ayarları',
                'db_table': 'web_settings',
            },
        ),
    ]
