# Generated by Django 5.2.13 on 2026-06-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_sensor_save_on_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.ForeignKey(help_text='İstasyonun ölçüm sistemi tipi (zorunlu)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stationtype', verbose_name='İstasyon Tipi'),
        ),
    ]
