# Generated by Django 5.2.13 on 2026-06-18 09:39

from django.db import migrations


def copy_sampler_to_scenarios(apps, schema_editor):
    """Alan kaldırılmadan önce istasyonun numune sensörünü, kendi sensörü
    tanımlı olmayan senaryolara taşı — mevcut sahalarda numune akışı kopmasın.

    Sensörü olmayan istasyona bağlı senaryolar boş kalır; motorda çalışmaz ve
    kütüphanede uyarı gösterilir (kasıtlı)."""
    Station = apps.get_model("api", "Station")
    Scenario = apps.get_model("sais_domain", "Scenario")

    station_sampler = {
        s.id: s.sample_request_sensor_id
        for s in Station.objects.exclude(sample_request_sensor__isnull=True)
    }
    if not station_sampler:
        return

    for scenario in Scenario.objects.filter(sampler_sensor__isnull=True).exclude(station__isnull=True):
        sensor_id = station_sampler.get(scenario.station_id)
        if sensor_id:
            scenario.sampler_sensor_id = sensor_id
            scenario.save(update_fields=["sampler_sensor"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_station_station_type'),
        # Scenario.sampler_sensor alanının (kopyalama hedefi) tarihsel durumda var
        # olması için — alan 0004'te eklendi. (0008 api.0019'a bağlı olduğundan
        # ona bağlanmak döngü yaratır.)
        ('sais_domain', '0004_scenario_scenariorun_scenariorunlog_scenariostep_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_sampler_to_scenarios, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='station',
            name='sample_request_sensor',
        ),
    ]
