# Generated by Django 5.2.13 on 2026-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_station_sample_request_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='machine_fingerprint',
            field=models.CharField(blank=True, default='', help_text='Token bu donanıma kilitliyse (node-lock) buraya yazılır; boşsa lisans makineye bağlı değil. Runtime fingerprint ile karşılaştırılır.', max_length=128, verbose_name='Bağlı Makine Parmak İzi'),
        ),
    ]
