# Generated by Django 5.2.13 on 2026-06-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_license_machine_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='station',
            name='port',
        ),
    ]
