# Generated by Django 5.2.13 on 2026-06-20 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_station_domain_remove_station_port'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Tesis Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='stationauthority',
            options={'ordering': ['station_id', 'user_id'], 'verbose_name': 'Tesis Yetkilisi', 'verbose_name_plural': 'Tesis Yetkilileri'},
        ),
        migrations.AlterModelOptions(
            name='stationtype',
            options={'ordering': ['code'], 'verbose_name_plural': 'Tesis Tipleri'},
        ),
        migrations.AlterField(
            model_name='alarmrule',
            name='offline_seconds',
            field=models.IntegerField(default=900, help_text='Son veriden bu kadar saniye geçtiyse tesis offline sayılır.', verbose_name='Offline Eşiği (sn)'),
        ),
        migrations.AlterField(
            model_name='alarmrule',
            name='rule_type',
            field=models.CharField(choices=[('analog', 'Ölçüm (Analog Limit)'), ('digital', 'Diagnostik (Dijital Kanal)'), ('offline', 'Tesis Offline')], default='analog', max_length=10, verbose_name='Alarm Türü'),
        ),
        migrations.AlterField(
            model_name='alarmrule',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_rules', to='api.station', verbose_name='Tesis'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(default='', help_text='Bu tesisteki bağlantının özgün adı', max_length=100, verbose_name='Bağlantı Adı'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api.station', verbose_name='Tesis'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='station',
            field=models.ForeignKey(blank=True, help_text='İsteğe bağlı — hatırlatıcıyı bir tesise bağla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='api.station', verbose_name='Tesis'),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Tesis Adresi', max_length=250, verbose_name='Tesis Adresi'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(help_text='Tesis Adı', max_length=100, verbose_name='Tesis Adı'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_type',
            field=models.ForeignKey(help_text='Tesisin ölçüm sistemi tipi (zorunlu)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stationtype', verbose_name='Tesis Tipi'),
        ),
        migrations.AlterField(
            model_name='stationauthority',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='api.station', verbose_name='Tesis'),
        ),
        migrations.AlterField(
            model_name='stationtype',
            name='name',
            field=models.CharField(help_text='Tesis tipi adı', max_length=100, verbose_name='Ad'),
        ),
    ]
