# Generated by Django 5.2.13 on 2026-06-20 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_station_options_alter_stationauthority_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, help_text='Kurulum sihirbazı en az bir kez tamamlandı mı?', verbose_name='Kurulum Tamamlandı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Tamamlayan')),
            ],
            options={
                'verbose_name': 'Kurulum Durumu',
                'verbose_name_plural': 'Kurulum Durumu',
                'db_table': 'setup_state',
            },
        ),
    ]
