# Generated by Django 5.2.13 on 2026-06-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_setupstate_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='tag',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Mimik/HMI bağlama için benzersiz etiket. Boş bırakılırsa kayıtta parametre kodundan otomatik üretilir (gerçek SCADA'daki gibi).", max_length=80, verbose_name='SCADA Etiketi (Tag)'),
        ),
    ]
