# Generated by Django 5.2.13 on 2026-07-02 20:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_seed_full_status_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Rapor Adı')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('blocks', models.JSONField(blank=True, default=list, help_text='Sıralı blok listesi — editör tarafından yazılır (JSON).', verbose_name='Blok Tanımları')),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=8, verbose_name='Sayfa Boyutu')),
                ('orientation', models.CharField(choices=[('portrait', 'Dikey'), ('landscape', 'Yatay')], default='portrait', max_length=12, verbose_name='Yönlendirme')),
                ('header_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Üst Bilgi')),
                ('footer_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Alt Bilgi')),
                ('show_logo', models.BooleanField(default=True, verbose_name='Logo Göster')),
                ('is_template', models.BooleanField(default=False, help_text='Yerleşik (seed) şablonlar silinemez.', verbose_name='Yerleşik Şablon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Güncelleme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Rapor Şablonu',
                'verbose_name_plural': 'Rapor Şablonları',
                'db_table': 'report_template',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Etkin')),
                ('period', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık')], default='daily', max_length=10, verbose_name='Periyot')),
                ('time_of_day', models.TimeField(default=datetime.time(7, 0), verbose_name='Çalışma Saati')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], help_text='Haftalık periyot için (0=Pazartesi).', null=True, verbose_name='Haftanın Günü')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Aylık periyot için (1-28).', null=True, verbose_name='Ayın Günü')),
                ('output_pdf', models.BooleanField(default=True, verbose_name='PDF Üret')),
                ('output_excel', models.BooleanField(default=False, verbose_name='Excel Üret')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='E-posta Gönder')),
                ('recipients', models.TextField(blank=True, default='', help_text='Virgül veya satır ile ayrılmış e-posta adresleri.', verbose_name='Alıcılar')),
                ('email_subject', models.CharField(default='{report_name} - {date}', help_text='Placeholder: {report_name}, {date}', max_length=200, verbose_name='E-posta Konusu')),
                ('email_body', models.TextField(blank=True, default='', help_text='Placeholder: {report_name}, {date}. Boşsa varsayılan gövde kullanılır.', verbose_name='E-posta Gövdesi')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Sonraki Çalışma')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Çalışma')),
                ('last_status', models.CharField(blank=True, default='', max_length=16, verbose_name='Son Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.reporttemplate', verbose_name='Rapor Şablonu')),
            ],
            options={
                'verbose_name': 'Rapor Zamanlaması',
                'verbose_name_plural': 'Rapor Zamanlamaları',
                'db_table': 'report_schedule',
                'ordering': ['template__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Üretim anındaki ad (şablon silinse de geçmişte kalır).', max_length=150, verbose_name='Şablon Adı')),
                ('status', models.CharField(choices=[('running', 'Üretiliyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], db_index=True, default='running', max_length=10, verbose_name='Durum')),
                ('trigger', models.CharField(choices=[('auto', 'Otomatik'), ('manual', 'Manuel')], default='manual', max_length=10, verbose_name='Tetikleyici')),
                ('reference_time', models.DateTimeField(help_text="Göreli zaman pencerelerinin çözüldüğü 'şimdi'.", verbose_name='Referans Zamanı')),
                ('pdf_file', models.CharField(blank=True, default='', help_text='REPORTS_DIR altındaki çıplak dosya adı.', max_length=255, verbose_name='PDF Dosyası')),
                ('xlsx_file', models.CharField(blank=True, default='', max_length=255, verbose_name='Excel Dosyası')),
                ('pdf_size', models.BigIntegerField(default=0, verbose_name='PDF Boyutu (byte)')),
                ('xlsx_size', models.BigIntegerField(default=0, verbose_name='Excel Boyutu (byte)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('error', models.TextField(blank=True, default='', verbose_name='Hata / Uyarı')),
                ('email_status', models.CharField(blank=True, choices=[('', '—'), ('sent', 'Gönderildi'), ('partial', 'Kısmen Gönderildi'), ('failed', 'Gönderilemedi')], default='', max_length=10, verbose_name='E-posta Durumu')),
                ('email_info', models.TextField(blank=True, default='', verbose_name='E-posta Detayı')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Tetikleyen Kullanıcı')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='api.reportschedule', verbose_name='Zamanlama')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='api.reporttemplate', verbose_name='Rapor Şablonu')),
            ],
            options={
                'verbose_name': 'Üretilen Rapor',
                'verbose_name_plural': 'Üretilen Raporlar',
                'db_table': 'generated_report',
                'ordering': ['-started_at'],
            },
        ),
    ]
