# Generated by Django 5.2.13 on 2026-07-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_reporttemplate_reportschedule_generatedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlatest',
            name='last_digital_change_at',
            field=models.DateTimeField(blank=True, help_text="Dijital sensörün aktif/pasif durumu en son ne zaman değişti. İletişim hatası kaynaklı değişimler (value None) sayılmaz — anasayfa Dijital Kanallar 'Son Değişim' sütununu besler.", null=True, verbose_name='Son Durum Değişim Zamanı'),
        ),
        migrations.AddField(
            model_name='sensorlatest',
            name='last_digital_state',
            field=models.BooleanField(blank=True, help_text='Dijital sensörün son GEÇERLİ okumadaki ham aktif/pasif durumu (iletişim/decode hatası okumaları hariç). last_digital_change_at karşılaştırma referansı.', null=True, verbose_name='Son Dijital Durum'),
        ),
    ]
