# Generated by Django 5.2.13 on 2026-07-17 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_sensorlatest_last_digital_change_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, help_text='classify_comm_error kodu: timeout/conn_reset/illegal_address/decode/...', max_length=32, verbose_name='Kategori')),
                ('source', models.CharField(blank=True, default='', help_text='config (biz) / device / network / line / ambiguous', max_length=16, verbose_name='Kaynak Yorumu')),
                ('status_code', models.IntegerField(blank=True, help_text="persist_reading'e yazılan kod (8=İletişim, 4=Geçersiz Veri).", null=True, verbose_name='Status Kodu')),
                ('detail', models.CharField(blank=True, default='', max_length=500, verbose_name='Ham Hata Metni')),
                ('time_iso', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zaman')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_errors', to='api.connection', verbose_name='Bağlantı')),
                ('sensor', models.ForeignKey(blank=True, help_text='Boş = bağlantı-seviyesi hata (tüm sensörleri etkiler; ör. bağlantı açılamadı).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_errors', to='api.sensor', verbose_name='Sensör')),
            ],
            options={
                'verbose_name_plural': 'İletişim Hata Olayları',
                'db_table': 'comm_error_event',
                'ordering': ['-time_iso'],
                'indexes': [models.Index(fields=['connection', '-time_iso'], name='commerr_conn_time_idx'), models.Index(fields=['category', '-time_iso'], name='commerr_cat_time_idx')],
            },
        ),
    ]
