# Generated by Django 5.2.13 on 2026-07-17 08:51

from django.db import migrations, models


def bump_inert_default(apps, schema_editor):
    """retry_count artık pymodbus'a bağlandı; eskiden ölüydü (pymodbus örtük 3
    kullanıyordu). Mevcut satırlardaki inert eski-default 1'i 3'e çekerek çalışan
    davranışı KORU (aksi halde saha güncellemesinde 4→2 denemeye düşerdi). Sadece
    dokunulmamış default (1) taşınır; kullanıcı elle başka değer girdiyse korunur.
    """
    Connection = apps.get_model('api', 'Connection')
    Connection.objects.filter(retry_count=1).update(retry_count=3)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_commerrorevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='retry_count',
            field=models.IntegerField(default=3, help_text="Cevapsız okumada pymodbus ek deneme sayısı. Toplam deneme = 1 + retry; her deneme timeout_ms kadar bekler (ör. retry=3, timeout=2000 → cevapsız okuma en fazla ~8 sn bloklar). 0 = tek deneme (en hızlı). Cevap vermeyen/yavaş noktalarda düşürmek poll cycle'ı hızlandırır.", verbose_name='Retry Sayısı'),
        ),
        migrations.RunPython(bump_inert_default, migrations.RunPython.noop),
    ]
