# Generated by Django 5.2.13 on 2026-09-15 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_connection_retry_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('export', 'Dışa Aktarım'), ('import', 'İçe Aktarım')], max_length=10, verbose_name='Yön')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('running', 'Uygulanıyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], default='pending', max_length=10, verbose_name='Durum')),
                ('filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Dosya Adı')),
                ('path', models.CharField(blank=True, default='', help_text='İçe aktarımda yüklenen dosyanın BACKUP_DIR altındaki yolu.', max_length=500, verbose_name='Tam Yol')),
                ('sections', models.JSONField(blank=True, default=list, verbose_name='Bölümler')),
                ('source_app_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Kaynak Sürüm')),
                ('source_hostname', models.CharField(blank=True, default='', max_length=255, verbose_name='Kaynak Makine')),
                ('exported_at', models.CharField(blank=True, default='', max_length=64, verbose_name='Dışa Aktarım Zamanı')),
                ('compatibility', models.CharField(blank=True, default='', max_length=10, verbose_name='Uyumluluk')),
                ('counts', models.JSONField(blank=True, default=dict, verbose_name='Kayıt Sayıları')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Sonuç')),
                ('error', models.TextField(blank=True, default='', verbose_name='Hata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('safety_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_transfers', to='api.databasebackup', verbose_name='Güvenlik Yedeği')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Konfigürasyon Aktarımı',
                'verbose_name_plural': 'Konfigürasyon Aktarımları',
                'db_table': 'config_transfer',
                'ordering': ['-created_at'],
            },
        ),
    ]
