# Generated by Django 5.2.13 on 2026-09-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_config_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='single_session',
            field=models.BooleanField(default=False, help_text="Cihaz aynı anda yalnız BİR TCP oturumu kabul ediyorsa açın (Mikrodev vb. küçük PLC'ler). Açıkken okuma turu biter bitmez soket kapatılır; böylece tüm worker process'leri boyunca aynı anda tek bağlantı açık kalır ve cihaz eski oturumu düşürdüğü için oluşan 'Connection reset by peer' / 'Broken pipe' hataları biter. Kapalıyken soket kalıcı tutulur (varsayılan, daha hızlı).", verbose_name='Tek Oturumlu Cihaz'),
        ),
    ]
