# Generated by Django 5.2.13 on 2026-06-12 22:03

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('doc_type', models.CharField(choices=[('technical_doc', 'Teknik Dokümantasyon'), ('comparison_test', 'Bütünleşik Karşılaştırma Testleri'), ('maintenance_form', 'Periyodik Bakım Formu'), ('minutes', 'Tutanaklar'), ('sensor_catalog', 'Sensör Katalogları'), ('sensor_brochure', 'Sensör Broşürleri'), ('other', 'Diğer')], db_index=True, default='other', max_length=32, verbose_name='Belge Türü')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('file', models.FileField(upload_to=dashboard.models.document_upload_path, verbose_name='Dosya')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Orijinal Dosya Adı')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dosya Boyutu (bayt)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='İçerik Tipi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yüklenme Tarihi')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Doküman',
                'verbose_name_plural': 'Dokümanlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
