# Generated by Django 5.2.13 on 2026-06-20 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MimicScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ekran Adı')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Fabric.js canvas.toJSON() çıktısı (objeler + bağlama meta verisi).', verbose_name='Tuval Verisi')),
                ('thumbnail', models.TextField(blank=True, default='', help_text='Galeri kartı için küçük base64 data-URL önizleme.', verbose_name='Önizleme (base64 PNG)')),
                ('width', models.PositiveIntegerField(default=1280, verbose_name='Genişlik (px)')),
                ('height', models.PositiveIntegerField(default=720, verbose_name='Yükseklik (px)')),
                ('background', models.CharField(default='#f5f8fa', max_length=32, verbose_name='Arka Plan Rengi')),
                ('is_template', models.BooleanField(default=False, help_text='Yerleşik şablonlar silinemez (kopyalanıp düzenlenebilir).', verbose_name='Yerleşik Şablon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Son Güncelleme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mimic_screens', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Mimik Ekranı',
                'verbose_name_plural': 'Mimik Ekranları',
                'ordering': ['-updated_at'],
            },
        ),
    ]
