# Generated by Django 5.2.13 on 2026-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mimicscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimicscreen',
            name='kind',
            field=models.CharField(choices=[('2d', '2B (Fabric.js)'), ('3d', '3B (Three.js)')], db_index=True, default='2d', help_text='2B: Fabric.js tuval editörü. 3B: Three.js sahne editörü. Kayıt oluşturulduktan sonra DEĞİŞTİRİLEMEZ.', max_length=2, verbose_name='Tasarım Türü'),
        ),
        migrations.AlterField(
            model_name='mimicscreen',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text="2B'de Fabric.js canvas.toJSON() çıktısı; 3B'de mimic3d/1 sahne belgesi (objeler + bağlama meta verisi).", verbose_name='Tuval / Sahne Verisi'),
        ),
    ]
