# Generated by Django 5.2.13 on 2026-04-18 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvisoftChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envi_channel_id', models.IntegerField(help_text='Envisoft sistemindeki kanal numarası', verbose_name='Envisoft Kanal ID')),
                ('parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envisoft', to='api.parameter', verbose_name='Parametre')),
            ],
            options={
                'verbose_name_plural': 'Envisoft Kanal Eşlemeleri',
                'db_table': 'sais_envisoft_channel',
                'ordering': ['envi_channel_id'],
            },
        ),
    ]
