# Generated by Django 5.2.13 on 2026-06-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_enabled', models.BooleanField(default=True, help_text="Kapalıysa Bakanlık SIM'e SendData çağrıları atlanır.", verbose_name='SIM Veri İletimi')),
                ('envisoft_enabled', models.BooleanField(default=True, help_text='Kapalıysa Envisoft SendData çağrıları atlanır.', verbose_name='Envisoft Veri İletimi')),
                ('polling_enabled', models.BooleanField(default=True, help_text='Kapalıysa dispatch_polls bağlantı enqueue etmez.', verbose_name='Sensör Okuması (Polling)')),
                ('manual_wash_duration_minutes', models.IntegerField(default=5, help_text='Manuel yıkama başlatıldığında varsayılan süre.', verbose_name='Manuel Yıkama Süresi (dk)')),
                ('weekly_wash_duration_minutes', models.IntegerField(default=20, help_text='Haftalık yıkama başlatıldığında varsayılan süre.', verbose_name='Haftalık Yıkama Süresi (dk)')),
                ('wash_active_kind', models.CharField(blank=True, choices=[('manual', 'Manuel Yıkama'), ('weekly', 'Haftalık Yıkama')], max_length=10, null=True, verbose_name='Aktif Yıkama Tipi')),
                ('wash_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Yıkama Başlangıcı')),
                ('wash_ends_at', models.DateTimeField(blank=True, help_text='Bu zaman geçtikten sonra yıkama otomatik sonlanır.', null=True, verbose_name='Yıkama Bitişi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Sistem Anahtarı',
                'verbose_name_plural': 'Sistem Anahtarları',
                'db_table': 'sais_system_switch',
            },
        ),
        migrations.CreateModel(
            name='EnvisoftChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envi_channel_id', models.IntegerField(help_text='Envisoft sistemindeki kanal numarası', verbose_name='Envisoft Kanal ID')),
                ('parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envisoft', to='api.parameter', verbose_name='Parametre')),
            ],
            options={
                'verbose_name_plural': 'Envisoft Kanal Eşlemeleri',
                'db_table': 'sais_envisoft_channel',
                'ordering': ['envi_channel_id'],
            },
        ),
        migrations.CreateModel(
            name='SaisCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text="Bakanlık'ın SAIS kabini için atadığı benzersiz kimlik", max_length=100, verbose_name='Bakanlık SIM ID')),
                ('code', models.CharField(help_text='Bakanlık istasyon kodu (örn. 30060001)', max_length=50, verbose_name='İstasyon Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Kabin Adı')),
                ('data_period', models.IntegerField(blank=True, default=1, help_text="Bakanlık'a veri gönderim periyodu", null=True, verbose_name='Veri Periyodu (dk)')),
                ('auth_username', models.CharField(max_length=50, verbose_name='Bakanlık Kullanıcı Adı')),
                ('auth_secret', models.CharField(max_length=255, verbose_name='Bakanlık Şifresi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sais_cabinets', to='api.station', verbose_name='İstasyon')),
            ],
            options={
                'verbose_name_plural': 'SAIS Kabin Kayıtları',
                'db_table': 'sais_cabinet',
                'ordering': ['created_at'],
            },
        ),
    ]
