# Generated by Django 5.2.13 on 2026-04-19 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_remotedevice'),
        ('sais_domain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaisCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text="Bakanlık'ın SAIS kabini için atadığı benzersiz kimlik", max_length=100, verbose_name='Bakanlık SIM ID')),
                ('code', models.CharField(help_text='Bakanlık istasyon kodu (örn. 30060001)', max_length=50, verbose_name='İstasyon Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Kabin Adı')),
                ('data_period', models.IntegerField(blank=True, default=1, help_text="Bakanlık'a veri gönderim periyodu", null=True, verbose_name='Veri Periyodu (dk)')),
                ('auth_username', models.CharField(max_length=50, verbose_name='Bakanlık Kullanıcı Adı')),
                ('auth_secret', models.CharField(max_length=255, verbose_name='Bakanlık Şifresi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sais_cabinets', to='api.station', verbose_name='İstasyon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SAIS Kabin Kayıtları',
                'db_table': 'sais_cabinet',
                'ordering': ['created_at'],
            },
        ),
    ]
