# Generated by Django 5.2.13 on 2026-06-06 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais_domain', '0002_saiscabinet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_enabled', models.BooleanField(default=True, help_text="Kapalıysa Bakanlık SIM'e SendData çağrıları atlanır.", verbose_name='SIM Veri İletimi')),
                ('envisoft_enabled', models.BooleanField(default=True, help_text='Kapalıysa Envisoft SendData çağrıları atlanır.', verbose_name='Envisoft Veri İletimi')),
                ('polling_enabled', models.BooleanField(default=True, help_text='Kapalıysa dispatch_polls bağlantı enqueue etmez.', verbose_name='Sensör Okuması (Polling)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Sistem Anahtarı',
                'verbose_name_plural': 'Sistem Anahtarları',
                'db_table': 'sais_system_switch',
            },
        ),
    ]
