# Generated by Django 5.2.13 on 2026-06-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_publiciprecord'),
        ('sais_domain', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemswitch',
            name='last_sim_success_at',
            field=models.DateTimeField(blank=True, help_text='Bakanlık SendData çağrısının en son 200 (kabul) döndüğü an.', null=True, verbose_name="SIM'e Son İletim Zamanı"),
        ),
        migrations.AddField(
            model_name='systemswitch',
            name='last_sim_success_readtime',
            field=models.CharField(blank=True, help_text="Bakanlık'ın 200 ile kabul ettiği verinin dakika damgası.", max_length=25, null=True, verbose_name="SIM'e İletilen Son Veri Tarihi"),
        ),
        migrations.CreateModel(
            name='SimStatusPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallback_status_code', models.IntegerField(default=1, help_text='Engellenen statusların yerine yazılacak StatusCode.code (varsayılan 1 = Veri Geçerli).', verbose_name='Yerine Gönderilecek Kod')),
                ('configured', models.BooleanField(default=False, help_text='Yönetici en az bir kez kaydetti mi? False iken filtre uygulanmaz.', verbose_name='Yapılandırıldı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('blocked_statuses', models.ManyToManyField(blank=True, help_text="İşaretli statuslar Bakanlık'a iletilmez; yerine fallback kod gönderilir.", related_name='+', to='api.statuscode', verbose_name="SIM'e Gönderilmeyen Statuslar")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'SIM Status Politikası',
                'verbose_name_plural': 'SIM Status Politikaları',
                'db_table': 'sais_sim_status_policy',
            },
        ),
    ]
