# Generated by Django 5.2.13 on 2026-06-06 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais_domain', '0003_systemswitch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemswitch',
            name='manual_wash_duration_minutes',
            field=models.IntegerField(default=5, help_text='Manuel yıkama başlatıldığında varsayılan süre.', verbose_name='Manuel Yıkama Süresi (dk)'),
        ),
        migrations.AddField(
            model_name='systemswitch',
            name='wash_active_kind',
            field=models.CharField(blank=True, choices=[('manual', 'Manuel Yıkama'), ('weekly', 'Haftalık Yıkama')], max_length=10, null=True, verbose_name='Aktif Yıkama Tipi'),
        ),
        migrations.AddField(
            model_name='systemswitch',
            name='wash_ends_at',
            field=models.DateTimeField(blank=True, help_text='Bu zaman geçtikten sonra yıkama otomatik sonlanır.', null=True, verbose_name='Yıkama Bitişi'),
        ),
        migrations.AddField(
            model_name='systemswitch',
            name='wash_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yıkama Başlangıcı'),
        ),
        migrations.AddField(
            model_name='systemswitch',
            name='wash_started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yıkamayı Başlatan'),
        ),
        migrations.AddField(
            model_name='systemswitch',
            name='weekly_wash_duration_minutes',
            field=models.IntegerField(default=20, help_text='Haftalık yıkama başlatıldığında varsayılan süre.', verbose_name='Haftalık Yıkama Süresi (dk)'),
        ),
    ]
