# Generated by Django 5.2.13 on 2026-06-12 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_readingfivemin'),
        ('sais_domain', '0003_systemswitch_last_sim_success_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Senaryo Adı')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('kind', models.CharField(choices=[('auto', 'Otomatik (eşik tetikli)'), ('ministry', 'Bakanlık Talepli')], default='auto', max_length=10, verbose_name='Senaryo Türü')),
                ('is_builtin', models.BooleanField(default=False, help_text='Yerleşik şablonlar silinemez (çoğaltılıp düzenlenebilir).', verbose_name='Yerleşik Şablon')),
                ('is_active', models.BooleanField(default=False, help_text='Aynı istasyon + tür için yalnız bir senaryo aktif olabilir.', verbose_name='Aktif')),
                ('enabled', models.BooleanField(default=True, verbose_name='Etkin')),
                ('avg_window', models.CharField(choices=[('5m', 'Son 5 dakika ortalaması'), ('15m', 'Son 15 dakika ortalaması')], default='15m', max_length=4, verbose_name='Ortalama Penceresi')),
                ('trigger_mode', models.CharField(choices=[('any', 'Herhangi biri aşınca'), ('all', 'Hepsi birlikte aşınca'), ('n_of_m', 'En az N tanesi aşınca')], default='any', max_length=10, verbose_name='Tetik Kombinasyonu')),
                ('trigger_n', models.IntegerField(default=1, help_text="trigger_mode='n_of_m' ise kaç parametrenin aşması gerektiği.", verbose_name='N (en az kaç parametre)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('sampler_sensor', models.ForeignKey(blank=True, help_text="Boşsa istasyonun sample_request_sensor'ı kullanılır.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.sensor', verbose_name='Numune Alıcı Sensör (override)')),
                ('station', models.ForeignKey(blank=True, help_text='Boş senaryolar şablondur; aktif edilmeden önce istasyon atanır.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_scenarios', to='api.station', verbose_name='İstasyon')),
            ],
            options={
                'verbose_name': 'Numune Senaryosu',
                'verbose_name_plural': 'Numune Senaryoları',
                'db_table': 'sais_scenario',
                'ordering': ['station', 'kind', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True, verbose_name='Tarih')),
                ('status', models.CharField(choices=[('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi')], default='in_progress', max_length=12, verbose_name='Durum')),
                ('is_ministry', models.BooleanField(default=False, verbose_name='Bakanlık Talepli')),
                ('trigger_at', models.DateTimeField(verbose_name='Tetik Zamanı')),
                ('last_step_order', models.IntegerField(default=-1, verbose_name='İşlenen Son Adım')),
                ('triggered_parameters', models.JSONField(blank=True, default=list, verbose_name='Tetikleyen Parametreler')),
                ('sample_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Numune Kodu')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='sais_domain.scenario', verbose_name='Senaryo')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.station', verbose_name='İstasyon')),
            ],
            options={
                'verbose_name': 'Senaryo Çalışması',
                'verbose_name_plural': 'Senaryo Çalışmaları',
                'db_table': 'sais_scenario_run',
                'ordering': ['-trigger_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zaman')),
                ('kind', models.CharField(choices=[('eval', 'Değerlendirme'), ('step', 'Adım'), ('skip', 'Atlandı')], default='eval', max_length=8, verbose_name='Tür')),
                ('step_order', models.IntegerField(blank=True, null=True, verbose_name='Adım Sırası')),
                ('averages', models.JSONField(blank=True, default=dict, verbose_name='Ortalamalar')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='Mesaj')),
                ('skipped_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Atlanma Nedeni')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='sais_domain.scenariorun', verbose_name='Çalışma')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.station', verbose_name='İstasyon')),
            ],
            options={
                'verbose_name': 'Senaryo Log',
                'verbose_name_plural': 'Senaryo Logları',
                'db_table': 'sais_scenario_run_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('label', models.CharField(blank=True, default='', max_length=150, verbose_name='Adım Adı')),
                ('after_seconds', models.IntegerField(default=0, help_text='Tetik anından bu kadar saniye sonra adım işlenir.', verbose_name='Tetikten Sonra (sn)')),
                ('require_still_exceeded', models.BooleanField(default=False, help_text='Açıksa, vade geldiğinde tetik koşulu hâlâ geçerliyse çalışır.', verbose_name='Koşul Hâlâ Sağlanmalı')),
                ('actions', models.JSONField(blank=True, default=list, help_text='Aksiyon listesi: notify / sampler_on / sampler_off / ministry_get_code / sim_sample_start / sim_sample_complete / sim_sample_error / send_diagnostic.', verbose_name='Aksiyonlar')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='sais_domain.scenario', verbose_name='Senaryo')),
            ],
            options={
                'verbose_name': 'Senaryo Adımı',
                'verbose_name_plural': 'Senaryo Adımları',
                'db_table': 'sais_scenario_step',
                'ordering': ['scenario', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Alt Sınır')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Üst Sınır')),
                ('ministry_param_code', models.CharField(blank=True, default='', help_text='GetSampleCode için; boşsa parametre adı kullanılır.', max_length=50, verbose_name='Bakanlık Parametre Kodu')),
                ('enabled', models.BooleanField(default=True, verbose_name='Etkin')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.parameter', verbose_name='Parametre')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='sais_domain.scenario', verbose_name='Senaryo')),
            ],
            options={
                'verbose_name': 'Senaryo Parametresi',
                'verbose_name_plural': 'Senaryo Parametreleri',
                'db_table': 'sais_scenario_parameter',
                'ordering': ['scenario', 'parameter'],
                'constraints': [models.UniqueConstraint(fields=('scenario', 'parameter'), name='sais_scenario_param_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='scenariorun',
            index=models.Index(fields=['station', '-run_date'], name='sais_run_station_date_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariorunlog',
            index=models.Index(fields=['station', '-created_at'], name='sais_runlog_station_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenariostep',
            constraint=models.UniqueConstraint(fields=('scenario', 'order'), name='sais_scenario_step_unique'),
        ),
    ]
