# Generated by Django 5.2.13 on 2026-06-12 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_readingfivemin'),
        ('sais_domain', '0004_scenario_scenariorun_scenariorunlog_scenariostep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tasarım Adı')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('graph', models.JSONField(blank=True, default=dict, help_text='Drawflow editor.export() çıktısı (node + bağlantı tanımı).', verbose_name='Graph (Drawflow)')),
                ('is_template', models.BooleanField(default=False, help_text='Yerleşik şablonlar silinemez (kopyalanıp düzenlenebilir).', verbose_name='Yerleşik Şablon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.station', verbose_name='İstasyon (bağlam)')),
            ],
            options={
                'verbose_name': 'Senaryo Tasarımı',
                'verbose_name_plural': 'Senaryo Tasarımları',
                'db_table': 'sais_scenario_graph',
                'ordering': ['-updated_at'],
            },
        ),
    ]
