# Generated by Django 5.2.13 on 2026-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais_domain', '0005_scenariograph'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemswitch',
            name='last_missing_check_at',
            field=models.DateTimeField(blank=True, help_text='GetMissingDates servisinin en son çalıştığı an (6 saatte bir).', null=True, verbose_name='Eksik Veri Son Kontrol'),
        ),
        migrations.AddField(
            model_name='systemswitch',
            name='last_missing_error',
            field=models.CharField(blank=True, help_text='Son kontrol hata ile bittiyse mesajı; başarılıysa boş.', max_length=300, null=True, verbose_name='Eksik Veri Son Hata'),
        ),
        migrations.AddField(
            model_name='systemswitch',
            name='last_missing_found_count',
            field=models.IntegerField(default=0, help_text="Son kontrolde Bakanlık'ın eksik bildirdiği dakika sayısı.", verbose_name='Son Bulunan Eksik Dakika'),
        ),
        migrations.AddField(
            model_name='systemswitch',
            name='last_missing_resent_count',
            field=models.IntegerField(default=0, help_text='Son kontrolde başarıyla yeniden gönderilen eksik dakika sayısı.', verbose_name='Son Yeniden Gönderilen'),
        ),
    ]
