# Generated by Django 5.2.13 on 2026-06-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais_domain', '0006_systemswitch_last_missing_check_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemswitch',
            name='facility_maint_duration_minutes',
            field=models.IntegerField(default=120, help_text='Tesis bakım modu başlatıldığında varsayılan süre.', verbose_name='Tesis Bakım Süresi (dk)'),
        ),
        migrations.AddField(
            model_name='systemswitch',
            name='station_maint_duration_minutes',
            field=models.IntegerField(default=60, help_text='İstasyon bakım modu başlatıldığında varsayılan süre.', verbose_name='İstasyon Bakım Süresi (dk)'),
        ),
        migrations.AlterField(
            model_name='systemswitch',
            name='wash_active_kind',
            field=models.CharField(blank=True, choices=[('manual', 'Manuel Yıkama'), ('weekly', 'Haftalık Yıkama'), ('station_maint', 'İstasyon Bakımda'), ('facility_maint', 'Tesis Bakımda')], max_length=20, null=True, verbose_name='Aktif Override Tipi'),
        ),
    ]
