# Generated by Django 5.2.13 on 2026-06-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_station_sample_request_sensor'),
        ('sais_domain', '0007_systemswitch_facility_maint_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='sampler_sensor',
            field=models.ForeignKey(blank=True, help_text='StartSample/sampler_on/off aksiyonlarının yazacağı dijital-out sensörü. sampler_on/off aksiyonu kullanan senaryolarda zorunlu; tanımlı değilse senaryo çalışmaz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.sensor', verbose_name='Numune Alıcı Sensör'),
        ),
    ]
