# Generated by Django 5.2.13 on 2026-06-20 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_station_options_alter_stationauthority_options_and_more'),
        ('sais_domain', '0008_alter_scenario_sampler_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saiscabinet',
            name='code',
            field=models.CharField(help_text='Bakanlık tesis kodu (örn. 30060001)', max_length=50, verbose_name='Tesis Kodu'),
        ),
        migrations.AlterField(
            model_name='saiscabinet',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sais_cabinets', to='api.station', verbose_name='Tesis'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Aynı tesis + tür için yalnız bir senaryo aktif olabilir.', verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Boş senaryolar şablondur; aktif edilmeden önce tesis atanır.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_scenarios', to='api.station', verbose_name='Tesis'),
        ),
        migrations.AlterField(
            model_name='scenariograph',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.station', verbose_name='Tesis (bağlam)'),
        ),
        migrations.AlterField(
            model_name='scenariorun',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.station', verbose_name='Tesis'),
        ),
        migrations.AlterField(
            model_name='scenariorunlog',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.station', verbose_name='Tesis'),
        ),
    ]
