# Generated by Django 5.2.13 on 2026-06-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais_domain', '0009_alter_saiscabinet_code_alter_saiscabinet_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimValidDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='Gün')),
                ('expected', models.IntegerField(default=0, help_text='O güne ait beklenen kayıt sayısı (geçmiş gün=1440, bugün=o ana kadar).', verbose_name='Beklenen Dakika')),
                ('received', models.IntegerField(default=0, verbose_name='Gelen Kayıt')),
                ('param_valid', models.JSONField(blank=True, default=dict, help_text='{parametre: doğrulanmış geçerli kayıt sayısı}', verbose_name='Parametre Geçerli Sayıları')),
                ('param_count', models.IntegerField(default=0, verbose_name='Parametre Sayısı')),
                ('finalized', models.BooleanField(default=False, help_text='Geçmiş gün; yeniden hesaplanmaz.', verbose_name='Kesinleşti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valid_days', to='sais_domain.saiscabinet', verbose_name='Kabin')),
            ],
            options={
                'verbose_name': 'Günlük Geçerli Veri',
                'verbose_name_plural': 'Günlük Geçerli Veriler',
                'db_table': 'sais_valid_day',
                'ordering': ['-day'],
                'constraints': [models.UniqueConstraint(fields=('cabinet', 'day'), name='sais_valid_day_unique')],
            },
        ),
    ]
