# Generated by Django 5.2.13 on 2026-06-30 20:36

import django.db.models.deletion
import sais_domain.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais_domain', '0010_simvalidday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_error_enabled', models.BooleanField(default=False, verbose_name='Bakanlık Veri Hatası Alarmı')),
                ('data_error_codes', models.JSONField(blank=True, default=sais_domain.models._default_data_error_codes, help_text='Bu Bakanlık status kodları tekrarlı görülürse bildir.', verbose_name='İzlenen Hata Kodları')),
                ('data_error_persist_minutes', models.IntegerField(default=5, help_text='Hata bu kadar dakikadan uzun tekrarlıysa bildir (anlık tek-sefer atlanır).', verbose_name='Tekrar Eşiği (dk)')),
                ('data_error_cooldown_minutes', models.IntegerField(default=60, help_text='Aynı hata için iki bildirim arası asgari süre.', verbose_name='Tekrar Bildirim Aralığı (dk)')),
                ('ssl_enabled', models.BooleanField(default=True, verbose_name='SSL Bitiş Uyarısı')),
                ('ssl_warn_days', models.IntegerField(default=3, verbose_name='SSL Uyarı (gün kala)')),
                ('calibration_enabled', models.BooleanField(default=True, verbose_name='Kalibrasyon Hatırlatma')),
                ('calibration_interval_days', models.IntegerField(default=30, help_text='Ayda 1 zorunlu → 30 gün.', verbose_name='Kalibrasyon Aralığı (gün)')),
                ('calibration_warn_days', models.IntegerField(default=1, verbose_name='Kalibrasyon Uyarı (gün kala)')),
                ('license_enabled', models.BooleanField(default=True, verbose_name='Lisans Bitiş Uyarısı')),
                ('license_warn_days', models.IntegerField(default=7, verbose_name='Lisans Uyarı (gün kala)')),
                ('poweroff_enabled', models.BooleanField(default=True, verbose_name='Kesinti (Açılma/Kapanma) Uyarısı')),
                ('poweroff_min_minutes', models.IntegerField(default=5, help_text='Bu süreden kısa kesintiler bildirilmez.', verbose_name='Asgari Kesinti Süresi (dk)')),
                ('notify_sms', models.BooleanField(default=True, verbose_name='SMS ile Bildir')),
                ('notify_email', models.BooleanField(default=True, verbose_name='E-posta ile Bildir')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Sistem Alarm Ayarı',
                'verbose_name_plural': 'Sistem Alarm Ayarları',
                'db_table': 'sais_system_alarm_settings',
            },
        ),
        migrations.CreateModel(
            name='SystemAlarmState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(max_length=30, verbose_name='Alarm Tipi')),
                ('ref_key', models.CharField(max_length=120, verbose_name='Referans')),
                ('last_notified_at', models.DateTimeField(verbose_name='Son Bildirim')),
                ('detail', models.CharField(blank=True, default='', max_length=300, verbose_name='Detay')),
            ],
            options={
                'verbose_name': 'Sistem Alarm Durumu',
                'verbose_name_plural': 'Sistem Alarm Durumları',
                'db_table': 'sais_system_alarm_state',
                'ordering': ['-last_notified_at'],
                'constraints': [models.UniqueConstraint(fields=('alarm_type', 'ref_key'), name='sais_alarm_state_unique')],
            },
        ),
    ]
