# Generated by Django 5.2.13 on 2026-07-03 08:47

import sais_domain.crypto
from django.db import migrations


def encrypt_existing(apps, schema_editor):
    """Mevcut düz-metin auth_secret'leri Fernet ile şifrele (idempotent).

    Field artık EncryptedCharField olduğundan .save() get_prep_value ile şifreler;
    from_db_value legacy düz metni olduğu gibi okur → yeniden kaydetmek şifreler.
    encrypt() 'fernet:' prefix'li değeri tekrar şifrelemez (güvenli tekrar).
    """
    SaisCabinet = apps.get_model('sais_domain', 'SaisCabinet')
    for cab in SaisCabinet.objects.all().iterator():
        cab.save(update_fields=['auth_secret'])


def noop_reverse(apps, schema_editor):
    """Geri alma: şifreli değerler düz metne çözülmez (fail-safe bırakılır)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sais_domain', '0011_systemalarmsettings_systemalarmstate'),
    ]

    operations = [
        # Önce kolonu genişlet (şifreli token 255'e sığmayabilir), sonra mevcut
        # değerleri şifrele.
        migrations.AlterField(
            model_name='saiscabinet',
            name='auth_secret',
            field=sais_domain.crypto.EncryptedCharField(max_length=512, verbose_name='Bakanlık Şifresi'),
        ),
        migrations.RunPython(encrypt_existing, noop_reverse),
    ]
