# Generated by Django 5.2.13 on 2026-08-19 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais_domain', '0012_alter_saiscabinet_auth_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemswitch',
            name='sim_accept_window_hours',
            field=models.IntegerField(default=48, help_text="Bakanlık bu kadar saat öncesine kadarki veriyi kabul eder (varsayılan 48). Kuyrukta bu süreyi aşan kayıtlar 'süresi doldu' işaretlenip atlanır. Bakanlık bakım vb. nedenle pencereyi geçici genişletirse burayı artırın; eksik veri servisi de aynı pencereyi kullanır.", verbose_name='Bakanlık Veri Kabul Penceresi (saat)'),
        ),
        migrations.CreateModel(
            name='SimOutboxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readtime', models.DateTimeField(help_text="Verinin ait olduğu dakika (saniye sıfırlanmış). Bakanlık'a gönderilen Readtime bu değerden üretilir.", verbose_name='Veri Zamanı')),
                ('period', models.SmallIntegerField(default=1, help_text='Kabinin veri periyodu (SendData Period alanı).', verbose_name='Periyot')),
                ('priority', models.SmallIntegerField(choices=[(0, 'Canlı'), (10, 'Geçmiş (eksik veri)')], default=0, help_text="Canlı dakikalar geçmiş veri backfill'inden önce gönderilir.", verbose_name='Öncelik')),
                ('source', models.CharField(choices=[('live', 'Dakikalık Yayın'), ('missing', 'Eksik Veri Servisi'), ('manual', 'Elle / Komut')], default='live', max_length=10, verbose_name='Kaynak')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Üretim anında dondurulmuş {parametre: değer, parametre_Status: kod} sözlüğü. Kayıt sonuçlanınca yer kaplamasın diye boşaltılır.', verbose_name='Veri (payload)')),
                ('status', models.CharField(choices=[('pending', 'Kuyrukta'), ('sending', 'Gönderiliyor'), ('sent', 'İletildi'), ('failed', 'Bakanlık Reddetti'), ('expired', 'Süresi Doldu'), ('skipped', 'Operatör Atladı')], db_index=True, default='pending', max_length=16, verbose_name='Durum')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Deneme Sayısı')),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Backoff sonrası bu andan önce tekrar denenmez.', verbose_name='Sonraki Deneme')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Deneme')),
                ('claimed_at', models.DateTimeField(blank=True, help_text='`sending` durumuna geçiş anı; worker çökerse bu damgadan hareketle kayıt kuyruğa geri alınır.', null=True, verbose_name='Kilitlenme Anı')),
                ('first_error_at', models.DateTimeField(blank=True, help_text="Bu kaydın ilk başarısız denemesi — 'kuyruk N dakikadır tıkalı' ölçümü buradan hesaplanır.", null=True, verbose_name='İlk Hata')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='İletim Zamanı')),
                ('last_error_kind', models.CharField(blank=True, default='', help_text='sais_domain.sim_errors kategorisi (timeout/conn_error/...).', max_length=20, verbose_name='Hata Tipi')),
                ('last_error', models.CharField(blank=True, default='', max_length=500, verbose_name='Son Hata')),
                ('last_http_status', models.IntegerField(blank=True, null=True, verbose_name='Son HTTP Kodu')),
                ('ministry_message', models.CharField(blank=True, default='', help_text='Ret hâlinde Bakanlık zarfındaki `message` alanı.', max_length=500, verbose_name='Bakanlık Mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_entries', to='sais_domain.saiscabinet', verbose_name='Kabin')),
            ],
            options={
                'verbose_name': 'SİM Veri Kuyruğu Kaydı',
                'verbose_name_plural': 'SİM Veri Kuyruğu',
                'db_table': 'sais_sim_outbox',
                'ordering': ['-readtime', '-id'],
                'indexes': [models.Index(condition=models.Q(('status__in', ['pending', 'sending'])), fields=['cabinet', 'priority', 'readtime'], name='sais_outbox_head_idx'), models.Index(condition=models.Q(('status', 'pending')), fields=['next_attempt_at'], name='sais_outbox_due_idx'), models.Index(fields=['status', '-readtime'], name='sais_outbox_st_rt_idx'), models.Index(fields=['cabinet', '-readtime'], name='sais_outbox_cab_rt_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'sending'])), fields=('cabinet', 'readtime'), name='sais_outbox_active_uniq')],
            },
        ),
    ]
