# Generated by Django 5.2.13 on 2026-08-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais_domain', '0013_systemswitch_sim_accept_window_hours_simoutboxentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemalarmsettings',
            name='sim_queue_backlog_threshold',
            field=models.IntegerField(default=30, help_text='Kuyrukta bu kadar dakikalık veri birikirse bildir.', verbose_name='Birikim Eşiği (dakika sayısı)'),
        ),
        migrations.AddField(
            model_name='systemalarmsettings',
            name='sim_queue_blocked_minutes',
            field=models.IntegerField(default=15, help_text='Baştaki veri bu kadar dakikadır iletilemiyorsa bildir.', verbose_name='Tıkanma Süresi Eşiği (dk)'),
        ),
        migrations.AddField(
            model_name='systemalarmsettings',
            name='sim_queue_cooldown_minutes',
            field=models.IntegerField(default=60, help_text='Aynı kabin için iki bildirim arası asgari süre.', verbose_name='Tekrar Bildirim Aralığı (dk)'),
        ),
        migrations.AddField(
            model_name='systemalarmsettings',
            name='sim_queue_enabled',
            field=models.BooleanField(default=True, help_text='Kuyruk tıkandığında veya birikmeye başladığında bildir.', verbose_name='Bakanlık Veri Kuyruğu Alarmı'),
        ),
    ]
