# Generated by Django 5.2.13 on 2026-09-14 08:23

import sais_domain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sais_domain', '0014_systemalarmsettings_sim_queue_backlog_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemalarmsettings',
            name='calibration_roles',
            field=models.JSONField(blank=True, default=sais_domain.models._default_alarm_roles, help_text='Bu alarmın bildirileceği kullanıcı rolleri (varsayılan: Operatör).', verbose_name='Kalibrasyon — Bildirim Rolleri'),
        ),
        migrations.AddField(
            model_name='systemalarmsettings',
            name='data_error_roles',
            field=models.JSONField(blank=True, default=sais_domain.models._default_alarm_roles, help_text='Bu alarmın bildirileceği kullanıcı rolleri (varsayılan: Operatör).', verbose_name='Bakanlık Veri Hatası — Bildirim Rolleri'),
        ),
        migrations.AddField(
            model_name='systemalarmsettings',
            name='license_roles',
            field=models.JSONField(blank=True, default=sais_domain.models._default_alarm_roles, help_text='Bu alarmın bildirileceği kullanıcı rolleri (varsayılan: Operatör).', verbose_name='Lisans — Bildirim Rolleri'),
        ),
        migrations.AddField(
            model_name='systemalarmsettings',
            name='poweroff_roles',
            field=models.JSONField(blank=True, default=sais_domain.models._default_alarm_roles, help_text='Bu alarmın bildirileceği kullanıcı rolleri (varsayılan: Operatör).', verbose_name='Kesinti — Bildirim Rolleri'),
        ),
        migrations.AddField(
            model_name='systemalarmsettings',
            name='sim_queue_roles',
            field=models.JSONField(blank=True, default=sais_domain.models._default_alarm_roles, help_text='Bu alarmın bildirileceği kullanıcı rolleri (varsayılan: Operatör).', verbose_name='Bakanlık Veri Kuyruğu — Bildirim Rolleri'),
        ),
        migrations.AddField(
            model_name='systemalarmsettings',
            name='ssl_roles',
            field=models.JSONField(blank=True, default=sais_domain.models._default_alarm_roles, help_text='Bu alarmın bildirileceği kullanıcı rolleri (varsayılan: Operatör).', verbose_name='SSL — Bildirim Rolleri'),
        ),
    ]
