# Generated by Django 5.2.13 on 2026-09-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_config_transfer'),
        ('sais_domain', '0015_systemalarmsettings_calibration_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text="Kapalıysa bu parametre SendData payload'una hiç yazılmaz.", verbose_name="Bakanlık'a Gönder")),
                ('ministry_defined', models.BooleanField(default=False, help_text='Son senkronizasyonda Bakanlık kanal listesinde bulundu mu.', verbose_name="Bakanlık'ta Tanımlı")),
                ('ministry_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Bakanlık Kanal Adı')),
                ('ministry_unit', models.CharField(blank=True, default='', max_length=100, verbose_name='Bakanlık Birimi')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Senkronizasyon')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_channels', to='sais_domain.saiscabinet', verbose_name='Kabin')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_channels', to='api.parameter', verbose_name='Parametre')),
            ],
            options={
                'verbose_name': 'Bakanlık Veri Kolonu',
                'verbose_name_plural': 'Bakanlık Veri Kolonları',
                'db_table': 'sais_sim_channel',
                'ordering': ['parameter__parameter_name'],
                'unique_together': {('cabinet', 'parameter')},
            },
        ),
    ]
